### ISSUE TITLE
Tag a Release?

### ISSUE THREAD

**Issue by dfornika** [B-UMMI/chewBBACA#1]
Hello,

I'd like to package chewBBACA up into a conda recipe for the bioconda channel. Do you have any plans to tag a release on this repository?

**Comment by jacarrico** [comment]
Hi, 
we definitely should tag a release! 
 We should have it done by next week and we will report it here when it done. 
And thank you in advance for the future conda recipe for Bioconda.

**Comment by jacarrico** [comment]
I actually went ahead and just did it. v1.0  (kashyyyk) is now available.

**Comment by dfornika** [comment]
I've submitted the pull request to the bioconda repo:

https://github.com/bioconda/bioconda-recipes/pull/5930

**Comment by dfornika** [comment]
The recipe is passing the bioconda continuous integration testing, so it should be ready to merge once they have a chance to review & approve it.

**Comment by jacarrico** [comment]
Thanks! Looking forward to test it

**Comment by dfornika** [comment]
The package is now available on the bioconda channel:

https://anaconda.org/bioconda/chewbbaca

`conda create -n chewbbaca -c bioconda chewbbaca`

`chewBBACA` is installed into the `lib` directory of the conda environment. I took the liberty of adding a symbolic link `bin/chewbbaca -> lib/chewBBACA.py` (a little easier to type).
