### ISSUE TITLE
Error with Maximum number of complete genomes! Does chewbbacca cant handle more complete genomes in CreateSchema?

### ISSUE THREAD

**Issue by bala-ruokavirasto** [B-UMMI/chewBBACA#101]
Hi,

When i tried with few genomes, the below code works:
chewBBACA.py CreateSchema -i test/ -o C.jejuni_schema_test --ptf Campylobacter_jejuni_training_file.trn --cpu 6

test folder contains few genomes.

However, when i try with 200 complete genomes of C.jejuni collected from Refseq, i get the below error:

(base) ubuntu@innuendo2-master-machine:/mnt/THL_RV/singularity_cache/shared_files/v1_test_C.jejuni$ chewBBACA.py CreateSchema -i test/ -o C.jejuni_schema_test --ptf Campylobacter_jejuni_training_file.trn --cpu 8

Now the test folder contains 200 plus complete genomes.

chewBBACA version: 2.8.4
Authors: Mickael Silva, Pedro Cerqueira, Rafael Mamede
Github: https://github.com/B-UMMI/chewBBACA
Wiki: https://github.com/B-UMMI/chewBBACA/wiki
Tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
Contacts: imm-bioinfo@medicina.ulisboa.pt

============================
  chewBBACA - CreateSchema
============================
Started at: 2021-06-03T04:02:35

Prodigal training file: Campylobacter_jejuni_training_file.trn
CPU cores: 8
BLAST Score Ratio: 0.6
Translation table: 11
Minimum sequence length: 201
Size threshold: 0.2
Word size: 5
Window size: 5
Clustering similarity: 0.2
Representative filter: 0.9
Intra-cluster filter: 0.9
Number of inputs: 203

Predicting gene sequences...

 [====================] 100%

Extracting coding sequences...

Error on cds_batch_extractor:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/utils/multiprocessing_operations.py", line 39, in function_helper
    results = input_args[-1](*input_args[0:-1])
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/utils/gene_prediction.py", line 235, in cds_batch_extractor
    total = save_extracted_cds(g, identifier, orf_file_path,
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/utils/gene_prediction.py", line 182, in save_extracted_cds
    genome_info = extract_genome_cds(reading_frames, contigs, 1)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/utils/gene_prediction.py", line 99, in extract_genome_cds
    sequence = contigs[contig_id]
KeyError: 'NC_022362.2'

 [                    ] 0%
Error on cds_batch_extractor:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/utils/multiprocessing_operations.py", line 39, in function_helper
    results = input_args[-1](*input_args[0:-1])
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/utils/gene_prediction.py", line 235, in cds_batch_extractor
    total = save_extracted_cds(g, identifier, orf_file_path,
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/utils/gene_prediction.py", line 182, in save_extracted_cds
    genome_info = extract_genome_cds(reading_frames, contigs, 1)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/utils/gene_prediction.py", line 99, in extract_genome_cds
    sequence = contigs[contig_id]
KeyError: 'NC_018709.2'

 [====================] 100%Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/chewBBACA.py", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/chewBBACA.py", line 1473, in main
    functions_info[process][1]()
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/utils/process_datetime.py", line 149, in wrapper
    func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/chewBBACA.py", line 193, in create_schema
    CreateSchema.main(**vars(args))
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/createschema/CreateSchema.py", line 1192, in main
    results = create_schema_seed(input_files, output_directory, schema_name,
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/createschema/CreateSchema.py", line 963, in create_schema_seed
    cds_files = extract_genes(fasta_files, prodigal_path,
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/createschema/CreateSchema.py", line 296, in extract_genes
    total_extracted = sum([f[2] for f in extracted_cdss])
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/CHEWBBACA/createschema/CreateSchema.py", line 296, in <listcomp>
    total_extracted = sum([f[2] for f in extracted_cdss])
IndexError: list index out of range

May i know how to still create the schema with all the 200 complete genomes??

Best Regards,
Bala

**Comment by rfm-targa** [comment]
Hello @bala-ruokavirasto,

I downloaded all complete genome assemblies for _C. jejuni_ with the [ncbi-genome-download](https://github.com/kblin/ncbi-genome-download) tool. I used the following command:

```
ncbi-genome-download -s refseq -F fasta -l complete -o cjejuni_complete_genomes -p 4 -r 4 --genera "Campylobacter jejuni" bacteria --flat-output
```

It downloaded 213 complete genome assemblies from RefSeq. I extracted all downloaded files in the `cjejuni_complete_genomes` directory with `gunzip` and executed chewBBACA's `CreateSchema` process to create a schema. The process completed without any issues. chewBBACA was able to process the genome assemblies that contain the nucleotide sequences with the `NC_022362` and `NC_018709` identifiers. I noticed, however, that the genome assembly you have used has a version of the `NC_018709` sequence, `NC_018709.2`, that is outdated and has been replaced (the current version of that sequence is `NC_018709.4`). I advise you to inspect the files with those sequences (GCF_000468915 and GCF_000302555) and look for problems.

To avoid issues related with genome assemblies, I think you should start by downloading the latest versions of the complete genomes for _C. jejuni_ (you can use the [ncbi-genome-download](https://github.com/kblin/ncbi-genome-download) tool and run the command I have used to download the latest set of 213 complete genomes). To execute chewBBACA, it is best to create a fresh conda environment and install chewBBACA v2.8.4 into that environment. It will install chewBBACA and all its dependencies, and should avoid some issues related with outdated or conflicting packages. Regardless of the method you choose to install chewBBACA, please make sure that you have installed chewBBACA's latest version and that you have also installed all dependencies (you can find installation instructions and the list of dependencies [here](https://github.com/B-UMMI/chewBBACA#0-setting-up-the-analysis)).

The issue you have encountered is not related with the number of genome assemblies. The CreateSchema process is optimized to process thousands of genome assemblies and should create a schema based on ~200 genome assemblies in under 5 minutes with 4 or more CPU cores.

Let us know if these suggestions help to solve the issue.

Best regards,
Rafael

**Comment by bala-ruokavirasto** [comment]
I solved the issue of not getting gene name ID by using the below code to get the accessions:

sed 's/ //g' new_protids.tsv | awk '{print $7,$8}' | sort -k 1 | awk '{print $2}' | sed 's:/: :g' | awk '{print $4}' > uniprot_accessions.txt

Then i used the below link to obtain the gene name ID by uploading the uniprot_accessions.txt file :
https://www.uniprot.org/uploadlists/

When i did the sorting of resulting gene name ID, i still see the same problem  of having many gene name ID as below:

FC283_00875
fcl
fcl
fcl
fcl
fcl
fdhA
fdhB1
fdhD

Bala

**Comment by ramirma** [comment]
@bala-ruokavirasto thank you for your continued interest in chewBBACA. I am glad that you managed to solve the schema creation problem with the latest version of chewBBACA. As for the annotation problem you mention I have two comments:

1) I am not sure what a concatenation of genomes would do to the resulting prodigal training file. Our usual approach is to create the prodigal training file based on a single high quality genome of the species of interest. You can see the one we used for campy here: https://github.com/mickaelsilva/prodigal_training_files

2) The uniprot annotations are based on the best hit of each locus to the uniprot's reference proteomes. The behavior you describe is not unusual. It may be due mostly to two things: i) in a few genomes there are several proteins that belong to the same family and would therefore have a high score hit to the same reference protein while still being recognized as two loci by chewBBACA [examples are phage associated proteins] or ii) in the same genomic context you may find in different strains proteins that while being the "same gene" are so different that chewBBACA identifies them as different loci [examples are surface exposed virulence proteins that sometimes include quite divergent clades].

As a general comment, please bear in mind that the automatic annotation provided by chewBBACA intends to be a guide for further human supervised annotation. The chewie-NS server contains examples of how these human annotations can look like. Incidentally, chewie-NS also contains a Campy schema that was created within the INNUENDO project (https://chewbbaca.online/species/4/schemas/1) which you may want to have a look at.

I hope to have clarified the issues you raised.

**Comment by bala-ruokavirasto** [comment]
Thanks for your clarification and suggestions! We want to create our own schema for custom-made in house analysis pipeline for WGS data of specific species. The reason is to cover more loci than the ones available in standard external schemas in different databases. Also, it is helpful for the species not available in the external schema. It will be also easy to maintain and update the schemas once new complete genomes added to the public databases by ourself. Please correct me if i am wrong in our approach with creating our own schema for these advantages. I believe that's the reason introduce the "CreateSchema" module for making custom made own schemas right? 

If creating own schema does not have any advantages then we dont want to spend time to implement this in our analysis. Kindly clarify this so that it will be very useful to design our analysis and just using the available schemas in different databases (Enterobase, Bigsdb, chewie-NS, etc...)!

Thanks in advance for your support on this problem!

Best Regards,
Bala

**Comment by ramirma** [comment]
Dear Bala,

The `CreateSchema` process was developed to give the users the possibility of creating schemas to better suit their own needs. Naturally, this would be specially important for species for which there are no schemas available. If there is a available public schema available, the decision to create your own schema would have to weight whether the schema available is sufficient for your purposes. The major advantage of using a schema already available and deposited in chewie-NS is that you will use the same nomenclature as other users of the same schema, allowing you to compare data directly. Furthermore, you can submit your new alleles to the public repository and download new alleles identified by others directly to your local chewBBACA instance, keeping your local and public versions in sync. In that way you can keep up to date with the most current nomenclature as well as contribute to it. Neither of these processes is mandatory.

The [campy schema](https://chewbbaca.online/species/4/schemas/1) deposited in chewie-NS was created back in 2017 but it was curated to be as stable as possible while affording a good discrimination.  It used the 5,691 genomes (including raw reads) available at the time we could assemble with quality with our pipeline [INNUca](https://github.com/B-UMMI/INNUca) pipeline, so it should capture a fair amount of variability and it was enough for the purposes of [INNUENDO](https://sites.google.com/site/innuendocon/). Of course you can adapt other schemas for use with chewBBACA using the `PrepExternalSchema` process. My suggestion would be to compare the discrimination you can obtain with these different schemas in a set of genomes of interest and decide what is best for your purpose. To create a schema is a lot of work. Updating it regularly is not only a lot of additional work but also risks making the results not comparable with previous analyses. I would not decide going down this path lightly, but of course you have to take into account the purpose of your schema.

I hope to have contributed for an informed decision on your part and we thank you again for your interest in chewBBACA.

Mario

**Comment by bala-ruokavirasto** [comment]
Thanks Mario for your clear explanation! I checked the chewie-NS and found only schema for wgMLST. Is there any available schemas for cgMLST as well in the same chewie-NS server?

Bala

**Comment by rfm-targa** [comment]
Hello @bala-ruokavirasto,

We determined the set of loci that constitute the core-genome for the INNUENDO schemas, but that list of loci is not available in chewie-NS. We are planning on adding that list to chewie-NS in the future, so that users can download and pass the list of loci to chewBBACA and only perform allele calling for the loci in the cgMLST. I have attached the file with the list of loci for the _C. jejuni_ cgMLST ([Cjejuni_cgMLST_ns_ids.txt](https://github.com/B-UMMI/chewBBACA/files/6727277/Cjejuni_cgMLST_ns_ids.txt)). You can pass that file to AlleleCall's `--gl` parameter and it will only perform allele calling for the loci in that list (more information [here](https://github.com/B-UMMI/chewBBACA#2--allele-call-using-the-wgmlst-schema)). You also need to download the [wgMLST schema](https://chewbbaca.online/species/4/schemas/1) for _C. jejuni_ from chewie-NS (you can use chewBBACA's `DownloadSchema` process, more information [here](https://chewie-ns.readthedocs.io/en/latest/user/download_api.html)).

I have also noticed that you have used an image named `mickaelsilva-chewbbaca_py3-latest` and that the `CreateSchema` process created a file named `proteinID_Genome.tsv` (the latest version no longer creates a file with this name, it creates a similar file named `cds_info.tsv`). Can you please confirm that you used an image with chewBBACA's latest version? You can get the image with the latest version (v2.8.4) [here](https://hub.docker.com/r/ummidock/chewbbaca). The `UniprotFinder` in the latest version also has a parameter, `--taxa`, to download reference proteomes from UniProt and extract annotation terms, including gene names, based on high sequence similarity (more information [here](https://github.com/B-UMMI/chewBBACA#:~:text=optional%3A%20determine%20annotations%20for%20loci%20in%20the%20schema)).

Let us know if you need more information.

Rafael

**Comment by bala-ruokavirasto** [comment]
Hi,

Thanks for your reply! Can you also provide us the core headers for four other species (Escherichia coli, Salmonella enterica, Listeria monocytogenes and Yersinia enterocolitica ) similarly as you provided for C.jejuni? 

Best Regards,
Bala

**Comment by rfm-targa** [comment]
Hello @bala-ruokavirasto,

Here are the files with the list of loci in the cgMLST for each species:

- [Ecoli_cgMLST_ns_ids.txt](https://github.com/B-UMMI/chewBBACA/files/6735682/Ecoli_cgMLST_ns_ids.txt)
- [Senterica_cgMLST_ns_ids.txt](https://github.com/B-UMMI/chewBBACA/files/6735684/Senterica_cgMLST_ns_ids.txt)
- [Yenterocolitica_cgMLST_ns_ids.txt](https://github.com/B-UMMI/chewBBACA/files/6735687/Yenterocolitica_cgMLST_ns_ids.txt)

The _L. monocytogenes_ schema is already a cgMLST schema created at Institut Pasteur and you do not need to provide a file with the subset of loci that constitute the cgMLST schema.

Let us know if there is any issue related with the download of the schemas from chewie-NS or while performing allele calling with the cgMLST.

Best regards,
Rafael

**Comment by bala-ruokavirasto** [comment]
Thanks a lot! It was very helpful.

Best Regards,
Bala
