### ISSUE TITLE
New alleles handling in chewBBACA while using external schemas

### ISSUE THREAD

**Issue by bala-ruokavirasto** [B-UMMI/chewBBACA#104]
Dear chewBBACA team,

I am wondering how the new alleles found in a isolates when using external schemas handled by chewbbaca. Will the new alleles automatically added to the database or do we need to write a seperate script to add those new alleles to the database?

To be specific, we used chewbie-NS server to update the external schemas and using latest chewbbaca to run the analysis. However, it would be nice to know what happens if there is new alleles in the isolates which is not represented in the schemas? Any insights will be useful and it is good to know if chewbbaca already has a way to handle this.

Best Regards,
Bala

**Comment by ramirma** [comment]
Dear Bala,

Thank you for your continued interest in chewBBACA. I am not quite sure what you mean. Are you using a schema available in chewie-NS? If not, what do you mean by we used chewie-NS server to update the external schemas? If you created a new schema it will not be present in chewie-NS, so you would need to submit the schema to chewie-NS to make it available there. Can you clarify exactly what you are trying to achieve? Is the "new" schema a subset of the loci present in a schema available in chewie-NS?

Looking forward to hearing from you,

Mario

**Comment by bala-ruokavirasto** [comment]
Yes! We are using external schema available already in chewie-NS. I like to know what if there is new allele present in the isolate and how it can be handled by chewbbaca?

Bala

**Comment by ramirma** [comment]
Novel alleles can be identified by chewBBACA when run on new isolates locally. If there are any new alleles identified, these are added to the local fasta file database of the relevant locus with a new number preceded by an asterisk. You can see a description of this behavior in [chewie-NS documentation](https://chewie-ns.readthedocs.io/en/latest/user/synchronize_api.html). Please note that these are your **_local_** files and not the information available at chewie-NS, i.e., the "novel" alleles will **_not be_** automatically submitted to the public database at chewie-NS. You can see in more detail how this works in the [chewie-NS tutorial](https://chewie-ns.readthedocs.io/en/latest/user/tutorial.html).

**Comment by bala-ruokavirasto** [comment]
Thanks a lot for your clear answer and that's exactly i am looking for.  We are interested to submit the new alleles found in the nomenclature server with below command:

chewBBACA.py SyncSchema -i path/to/schema --submit 

I just wonder how to get contributor rights to submit new alleles? Also, our institute might have multiple users and so Is it feasible to obtain contributor rights for all of them?

In addition, While doing Sync schema and send novel local alleles to the NS, Will the submitted new allele have some international nomenclature so that people dont submit redundant alleles as new alleles again and again? Or atleast some unique ID to unique new alleles? There is no clear info in the documentation about this. Any insights would be very helpful and thanks for the great tool :)

Bala

**Comment by ramirma** [comment]
Dear Bala,

As for the contributor rights, please [register with chewie-NS](https://chewbbaca.online/register) and then send us an email at  imm-bioinfo(at)medicina.ulisboa.pt. We do not do any manual curation, so the onus of the accuracy of the allele calls (influenced by the depth of coverage and quality of the assemblies) falls entirely on the users. We will be able to discuss this further through email.

Any alleles submitted to chewie-NS will be assigned allele numbers and deposited in the public database so that anyone else using the same schema will have access to these alleles and no "redundant alleles" can be submitted to the public database.
