### ISSUE TITLE
ExtractCgMLST doesn't read the input file

### ISSUE THREAD

**Issue by xyz0o** [B-UMMI/chewBBACA#106]
I am trying to run ChewBBaca.py in a docker, I have previously ran the AlleleCall the same way successfully but now I get the error that it cannot find the input file, I have tried giving the file name with full path and without the full path, but nothing changes. can you tell me where am I wrong?

![image](https://user-images.githubusercontent.com/77616805/142740288-316f86f6-1cf4-4b08-8328-e22c08f1a7b6.png)

**Comment by rfm-targa** [comment]
Greetings @xyz0o,

Could you find a solution to this issue? I noticed that you are using an outdated version, v2.0.15. Using the Docker image with the latest version, v2.8.5, might solve most issues and improve performance.

Rafael

**Comment by xyz0o** [comment]
Hi, yes, I once logged out and in again, and changed the path to the file from full path to the current: ~/tsv... to tsv/results_alleles_all.tsv, also -o tsv, it's weird but it worked!

**Comment by ramirma** [comment]
Thank you for getting back to us @xyz0o. I am glad that it worked for you, although we have no idea why this happened. Please bear in mind Rafael's suggestion to upgrade to the latest chewBBACA version: v2.8.5. We are constantly updating chewBBACA, not only with new features but also correcting issues that come to our attention.
