### ISSUE TITLE
How to find cgMLST of Staphylococcus pseudintermedius

### ISSUE THREAD

**Issue by sekhwal** [B-UMMI/chewBBACA#111]
I am using chewBBACA for identifying cgMLST of species Staphylococcus pseudintermedius. Please let me know if I am able to get it using the database to get the cgMLST information of the species.

Thank you,

Manoj

**Comment by ramirma** [comment]
Dear Manoj,

Sorry for not having responded sooner. If you are asking if there is already a publicly available schema for Staphylococcus pseudintermedius in [chewie-NS](https://chewbbaca.online/) there is no such schema. If you want to develop one, you can use chewBBACA to do so. I would suggest you look at the [wiki pages](https://github.com/B-UMMI/chewBBACA/wiki/1.-Schema-Creation).
Do not hesitate to contact us again if we can help with anything else.
Mario

**Comment by sekhwal** [comment]
Hi,

I installed chewBBACA using conda and followed all the steps of the following tutorials.
https://github.com/B-UMMI/chewBBACA
https://github.com/B-UMMI/chewBBACA_tutorial

I have got several output files such as (*.protein*.fasta, cgMLST.tsv, results_alleles.tsv, Genes_95%.txt).

Now, I have follow up questions.
1). How I can get cgMLST of my assembly genomes. I tried to find in the output files but the files contain a very large data but no cgMLST.
2). Once I am using the following command, it shows following error:

##chewBBACA.py JoinProfiles -p1 /cgMLST_95/cgMLST.tsv -p2 /results_alleles.tsv -o cgMLST_all.tsv
---------error-----------
JoinProfiles: error: unrecognized arguments: Staph_cgMLST/cgMLST/cgMLST.tsv Staph_cgMLST/Staph_AlleleCall/results_alleles.tsv 

Thank you!!

**Comment by sekhwal** [comment]
I have created a cgMLST schema for "Staphylococcus pseudintermedius" using chewBBACA, please let me know how to proceed to get cgMLST of my assembled genomes.

Thank you!

**Comment by sekhwal** [comment]
Hi, Please let me know how to proceed to identify cgMLST next after getting the schema of "Staphylococcus pseudintermedius".

**Comment by sekhwal** [comment]
Yes, I got the cgMLST from the schema using chewBBACA.py ExtractCgMLST but I am not sure where the cgMLST number. For instance, scaffold1.fasta belongs to 1252cgMLST. However, in the results of chewBBACa, the excel file contains large datasets.

**Comment by ramirma** [comment]
Dear Manoj,

I am not sure I understand what you mean. Could you send us the output files you got? If you prefer you can email us at imm-bioinfo@medicina.ulisboa.pt.

Mario

**Comment by sekhwal** [comment]
Hi, please let me know if there is any update about my query. Still I am trying to understand how to get cgST from the Schemes. I may not be correct to understand the way. Any clarification would be highly appreciated.
Thank you,
Manoj

**Comment by ireneortega** [comment]
I think @sekhwal wants to get the number for the cgST, that is a single value from the cgMLST chema. For example, the ST is obtained from the seven MLST loci. So, cgST would be similarly obtained from the cgMLST chema. I am also interested in this. For example, in [pubmlst.org](https://pubmlst.org/) you can get the the closest profile cgST when selecting cgMLST chema.

**Comment by ramirma** [comment]
Sorry, the issue was left dangling. chewBBACA does not provide a unique identifier or ST number for a given cgMLST profile. This is a difficult problem for which we do not have a solution currently implemented.

**Comment by rfm-targa** [comment]
Closing this issue. chewBBACA does not include a module to determine cgSTs, but the allele calling results can be analysed with other tools to get to that point. We added some suggestions in another issue's comments [here](https://github.com/B-UMMI/chewBBACA/issues/181#issuecomment-2151763378).
