### ISSUE TITLE
user-specified translation table doesnot match the one in the specified training file

### ISSUE THREAD

**Issue by Turner-L** [B-UMMI/chewBBACA#114]
Hi, 

I've tried to run a few genomes after setting up, but get the following error:

Starting Prodigal at: 15:37:14-01/02/2022
Training file: cgkpne-chew/KPNE-subsp_pneu_HS11286_genomic-referencegenome.fna
 [====================] 100%

Failed to predict genes for 16 genomes.
Info for failed cases stored in: prodigal_stderr.tsv
Please remove invalid inputs and try again.

The prodigal_stderr.tsv file then states:

"Warning: user-specified translation table doesnot match the one in the specified training file!"

Any ideas?

**Comment by rfm-targa** [comment]
Hello @Turner-L,

Could you please share the command that you used and the version of chewBBACA that you have installed? The file extension for a training file should be `.trn`, but chewBBACA is trying to use a file with the `.fna` extension that is used in FASTA files. Are you providing the training file through the `--ptf` parameter?

Rafael

**Comment by Turner-L** [comment]
Thank you. I hadn't created the training file correctly. I remade it using prodigal and with the --ptf parameter the programme worked well :)
