### ISSUE TITLE
--p <threshold> vs --t, --threshold THRESHOLD            

### ISSUE THREAD

**Issue by bala-ruokavirasto** [B-UMMI/chewBBACA#116]
Dear Chewbbaca Team,

There is some confusion of different parameter --p and --t mentioned for the same threshold. Could you clarify which one is right one to use?

$ singularity exec ummidock-chewbbaca-2.8.5.img chewBBACA.py ExtractCgMLST --help

chewBBACA version: 2.8.5
Authors: Mickael Silva, Pedro Cerqueira, Rafael Mamede
Github: https://github.com/B-UMMI/chewBBACA
Wiki: https://github.com/B-UMMI/chewBBACA/wiki
Tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
Contacts: imm-bioinfo@medicina.ulisboa.pt

=============================
  chewBBACA - ExtractCgMLST
=============================
Started at: 2022-02-08T09:55:50

usage:
Determine cgMLST:
  chewBBACA.py ExtractCgMLST -i <input_file> -o <output_directory>

Determine cgMLST based on non-default threshold:
  chewBBACA.py ExtractCgMLST -i <input_file> -o <output_directory>
                             **--p <threshold>**

Remove genes and genomes from matrix:
  chewBBACA.py ExtractCgMLST -i <input_file> -o <output_directory>
                             --r <genes2remove> --g <genomes2remove>

Determines the set of loci that constitute the core genome based on a threshold.

positional arguments:
  ExtractCgMLST

optional arguments:
  -h, --help                               show this help message and exit

  -i, --input-file INPUT_FILE              Path to input file containing a matrix with allelic
                                           profiles. (default: None)

  -o, --output-directory OUTPUT_DIRECTORY  Path to the directory where the process will store output
                                           files. (default: None)

  **--t, --threshold THRESHOLD**               Genes that constitute the core genome must be in a
                                           proportion of genomes that is at least equal to this
                                           value. (default: 1)

  --r, --genes2remove GENES2REMOVE         Path to file with a list of genes/columns to remove from
                                           the matrix (one gene identifier per line). (default:
                                           False)

  --g, --genomes2remove GENOMES2REMOVE     Path to file with a list of genomes/rows to remove from
                                           the matrix (one genome identifier per line). (default:
                                           False)

**Comment by rfm-targa** [comment]
Hello @bala-ruokavirasto,

The correct way to define the threshold is through the `--t` argument listed in the optional arguments section. Thank you for noticing this. It will be fixed in a future version.

Rafael
