### ISSUE TITLE
Requesting explanation of headers (_S_ and _CS"Number"_  for new allele variants in schema folders

### ISSUE THREAD

**Issue by bala-ruokavirasto** [B-UMMI/chewBBACA#128]
Dear chewbbaca Team,

I notice that the new allele variants got from the sample were added nicely with timestamps and sample name to trak it. However, it was not clear what is the explanation behind the naming _S_ and _CS"Number"._ in the header of new allele variants found. Could you kindly clarify?

>ERR024585-protein5964-40224-41877**_S_**FIXT-264-S1-L001-trim-spades3120-proc-filt-polished.fasta_04/03/2022T19:27:58_51
>ERR024585-protein5964-40224-41877**_S_**FIXT-265-S2-L001-trim-spades3120-proc-filt-polished.fasta_04/03/2022T19:44:36_52
>ERR024585-protein5964-40224-41877**_S_**FIXT-434-S7-L001-trim-spades3120-proc-filt-polished.fasta_04/03/2022T20:10:24_53
>ERR024585-protein5964-40224-41877**_S_**FIXT-268-S4-L001-trim-spades3120-proc-filt-polished.fasta_04/03/2022T20:19:57_54
>ERR024585-protein5964-40224-41877**_S_**FIXT-266-S6-L001-trim-spades3120-proc-filt-polished.fasta_05/03/2022T02:38:00_55
>ERR024585-protein5964-40224-41877**_S_**130307-S9-L001-trim-spades3120-proc-filt-polished.fasta_16/03/2022T20:54:20_56
>ERR024585-protein5964-40224-41877**_CS37_**122744-B-S1-L001-trim-spades3120-proc-filt-polished.fasta_17/03/2022T22:55:22_57
>ERR024585-protein5964-40224-41877**_S_**135109-S3-L001-trim-spades3120-proc-filt-polished.fasta_22/03/2022T12:40:00_58

Thanks in advance!

Best Regards,
Bala

**Comment by rfm-targa** [comment]
Hello @bala-ruokavirasto,

Sorry for the delayed response. The `S`, `CS` and `CD` tags are used to indicate if an allele is contained or contains another allele. The `S` tag means that when the allele was added to the schema it was not contained in or contained any other allele from the same locus. The `CS` tag means that the allele contains the allele with the specified allele identifier (e.g.: `CS37` means that the allele with identifier 37 is contained in that allele). The `CD` tag indicates that the allele is contained in other allele.
Hope to have clarified the usage of the `S`, `CS` and `CD` tags.

Rafael
