### ISSUE TITLE
[Errno 21] Is a directory: 'listeria_db/short'

### ISSUE THREAD

**Issue by kristyhoran** [B-UMMI/chewBBACA#13]
When running chewBBACA I consistently get this error. When running it by itself it will complete, however I am trying to incorporate it into a pipeline (snakemake) and this error is causing it to break (pipe fail). Is there something I can do to prevent this error?
Cheers
Kristy

**Comment by mickaelsilva** [comment]
As of now, folders inside the schema are ignored and consequently the error is no longer prompted. Just update chewBBACA to version 2.0.12 .

Cheers
