### ISSUE TITLE
ValueError: Missing some files from prodigal

### ISSUE THREAD

**Issue by davidmaimoun** [B-UMMI/chewBBACA#135]
Hi, 
Thank you for the great tool!

I encountered a issue when I ran the AllelCall for the salmonella specie

The PrepExternalSchema did work very good:
_Successfully adapted 2999/3001 genes present in the input schema._

But in the AllelCall process:
_ValueError: Missing some files from prodigal. 3 missing files out of 14_

I downloaded the prodigal file and did the prepExternaSchema again and again, but the issue persists

Could you help me please?

Thank you

**Comment by davidmaimoun** [comment]
It is working now that I deleted duplicate in my input file - I had two same sequences from different directories, and I joined them into a text file as input for the AlleleCall
I think that was the problem
May be you can confirm?

Thank you!

**Comment by rfm-targa** [comment]
Hello @davidmaimoun,

Thank you for your interest in chewBBACA. I confirm that duplicated inputs lead to issues after gene prediction with Prodigal. Different input files cannot share the same unique identifier and should not contain sequence records with the same identifiers.
This has been described in issue #108.
Let us know if you find other issues.

Rafael

**Comment by davidmaimoun** [comment]
Thank you very much Rafael
