### ISSUE TITLE
Allele Calling without prodigal

### ISSUE THREAD

**Issue by davidmaimoun** [B-UMMI/chewBBACA#136]
Hi, 
I need to chewBBaca to my Neisseria typing pipeline
I didn't find a prodigal file to neisseria meningitidis, and I would like to run the Allele call anyway
I tried but it didn't work

From the console:

"
It seems that your schema was created with chewBBACA 2.1.0 or lower.
It is highly recommended that you run the PrepExternalSchema process to guarantee full compatibility with the new chewBBACA version.
If you wish to continue, the AlleleCall process will convert the schema to v2.8.5, but will not determine if schema structure respects configuration values.
Do you wish to proceed?
y

Full path to the Prodigal training file:
"

It ask me to add the prodigal file, which I haven't.
I got the cgMLST scheme from pubMLST
And I would like to complete the pipeline without to tape anything to the console
Is it possible?

Thank you very much

**Comment by ramirma** [comment]
Dear @davidmaimoun ,

Thank you for your interest in chewBBACA. From what you describe you are trying to do allele calling with a schema from PubMLST with chewBBACA. chewBBACA recognizing this is offering to adapt the PubMLST schema so it can use it. The first step of chewBBACA is running prodigal to identify protein coding regions. For that to be reproducible it uses always the same training file, the one it is asking you for. In order for the conversion to proceed you need to provide one.

I suggest that you select a high quality genome (ideally fully closed genome from refseq) and generate a training file following the instruction in [prodigal's github](https://github.com/hyattpd/prodigal/wiki/Gene-Prediction-Modes#training-mode). You can then provide this file to chewBBACA. From then on it will be part of your schema and you no longer have to provide it.

I hope I clarified your point and hope that you are able to move forward.

Mario

**Comment by davidmaimoun** [comment]
It is working!

Thank you so much for your help and this incredible tool

**Comment by ramirma** [comment]
Glad it worked!

**Comment by ireneortega** [comment]
I got the same message when using the Campylobacter trining file provided by chewBBACA. I repeat the same command after creating the Prodigal training file as suggested @ramirma with a reference genome in .fasta format and got the same message again. Should I ask "yes" to the question `Do you wish to proceed?` in any case? Is everything correct anyways?

**Comment by ramirma** [comment]
@ireneortega can you clarify that you still have the error? If you have adapted the PubMLST  with chewBBACA you should not get that message again

**Comment by ireneortega** [comment]
@ramirma I repeated the execution and the error disappeared. I think it was something related with the name of the schema path
