### ISSUE TITLE
PrepExternalSchema not running for conda build

### ISSUE THREAD

**Issue by klgray25** [B-UMMI/chewBBACA#14]
Hello,

I have installed the conda environment for chewbbaca and am trying to use an external Salmonella wgMLST schema from Enterobase. I am running the PrepExternalSchema function on the downloaded fasta files as follows:

chewbbaca PrepExternalSchema -i PATH-TO-DIRECTORY --cpu 4

Whenever I do so, I just get the help message for chewbacca as output and the function doesn't run.

I can see that inside of the main function in chewBBACA.py, the exception is being caught when prep_schema() is run (which would be why the help message is printed). Inside of prep_schema(), it is line 360 proc = subprocess.Popen(args) that is not working. These lines seem to have been changed in the current version of chewBBACA on GitHub, so perhaps this has been fixed (just not in the conda build).

Please let me know how you recommend handling the situation and what I can do to get chewBBACA up and running for my analysis.

Best wishes,
Kristen

**Comment by mickaelsilva** [comment]
Hello Kristen,

there were some changes indeed on those lines but they were not related to this error, which is something that never happened before.

I would ask you to first try with the following small test set, just unzip it and run the command the same way you did before

[genes.zip](https://github.com/B-UMMI/chewBBACA/files/2268225/genes.zip)

Let me know if you were successful with this test set,

cheers

**Comment by klgray25** [comment]
Hello Mickael,

I'm afraid the test set you have attached produced the same result.

Best,
Kristen

**Comment by mickaelsilva** [comment]
Hello Kristen,

It could be some specific conda behavior, but I'm not familiar with it (the conda package wasn't done by me) and I'm not on the lab until next week.

In the meantime I can only suggest you to try installing it with pip3 (virtualenv preferably)  or the docker image at https://hub.docker.com/r/mickaelsilva/chewbbaca_py3/

Cheers

**Comment by klgray25** [comment]
Hi Mickael,

I installed it with pip and got it up and running.

It was still not working at first, but I realized that this was because my file extension was .fa and not .fasta. This was not the original problem with the original conda build though, as the conda version still doesn't work when the extension is .fasta.

Thanks for the assistance.

Best,
Kristen

**Comment by r0sies** [comment]
Hi,
I have the same error:

module load python/3.6.5
module load blast+/2.7.1

wget https://github.com/B-UMMI/chewBBACA/files/2268225/genes.zip
unzip genes.zip

chewBBACA.py PrepExternalSchema -i genes --cpu 2 -v
chewBBACA.py PrepExternalSchema -i genes --cpu 2 -v
chewBBACA version 2.0.12 by Mickael Silva at https://github.com/B-UMMI/chewBBACA
email contact: mickaelsilva@medicina.ulisboa.pt


ls
genes  genes.zip  prodigal_training_files
