### ISSUE TITLE
Allele calling threshold

### ISSUE THREAD

**Issue by mlarjim** [B-UMMI/chewBBACA#146]
Dear chewBBACA team,

I am wondering how chewBBACA determines that an allele is new, does it use a theshold?
According to chewBBACA documentation, **a new allele is inferred when it does not have an exact match in the schema but are highly similar to loci in the schema**. Does this mean that if an allele does not share the 100% of the nucleotides with any allele in the schema, it is classified as inferred, even if there is a single nucleotide difference? And if so, how can we modify this threshold?
What does "highly similar" in the above statement mean?

Thank you in advance
Best regards,
Maria Lara

**Comment by ramirma** [comment]
Dear Maria Lara,

Thank you for your interest in chewBBACA. As you indicate, chewBBACA will identify a novel allele if an allele in a query sequence is not 100% identical at the nucleotide level with an allele already in the schema. There is no way to change this threshold. ChewBBACA was written with typing in mind and so even a single SNP allows differentiating two isolates and we though of no use case where "ignoring" potentially discriminating information could be useful. This is such a basic principle that it is embedded in all that chewBBACA does. As for the sufficient similarity, this is evaluated by the BSR (blast score ratio) value of the protein encoded by the allele and a comparison to the mode size of the alleles in the locus. The default values for these are a BSR>0.6 and a variation in size <20% of the mode, but these can be changed by the user in parameters passed to chewBBACA.

I hope to have clarified your question and that chewBBACA will be useful for your application.

Mario

**Comment by mlarjim** [comment]
Dear Mario,
Thank you so much for your answer. Therefore, how does chewBBACA overcome the problem of sequencing errors? A new allele is inferred whenever it detects a new nucleotide substitution, but this allele may have been born in the sequencing process

**Comment by mlarjim** [comment]
Thank you for your quick and enlightening answer! I find particularly interesting the new option of chewbbaca v3.0 and was not aware of it...will this version be available to install using conda soon?

**Comment by ramirma** [comment]
@rfm-targa is working on making a conda release soon. We will also make available new documentation detailing all the new features. In the meantime you can always clone the repository!
