### ISSUE TITLE
SchemaEvaluator: html output files for individual gene cannot be displayed in browser

### ISSUE THREAD

**Issue by artmisk13** [B-UMMI/chewBBACA#159]
Hi!

After running SchemaEvaluator, I was not able to see the html output files for individual gene. I tried to open the files with Chrome, Safari, and Firefox; they all only showed the same white blank page. I tried to inspect the element and I can see that there are data in the html files (it's not an empty html file). I also made sure that I already enabled javascript in all my browsers. However, the summary html file for all the genes, from the same run, can be displayed. Thank you very much for your help!

**Comment by rfm-targa** [comment]
Hello @artmisk13,

Thank you for your interest in chewBBACA. We are aware that the SchemaEvaluator module is not fully working. Some changes to the JS libraries used to generate the report have introduced several issues in the loci reports. We're working to fix those issues in a separate branch ([SchemaEvaluator_fix](https://github.com/B-UMMI/chewBBACA/tree/SchemaEvaluator_fix)). We hope to have a new release with all the fixes soon. I'll let you know when it's out.

Rafael

**Comment by hkaspersen** [comment]
Hello!
Just to add to this issue, this seem to be the case for the main html report as well, if the report is taken out of its original location in the result directory. I hope in near future that I can send this html to someone without having to send the whole results directory with it! :)

**Comment by ramirma** [comment]
Just a quick note on @hkaspersen comment. Although we are working to fix the SchemaEvaluator, some of what will be displayed has to do with showing results stored in the result directory so it will be hard to have a standalone html file with all the information although we will try to make a streamlined version of an html that can be more easily shared. You can of course compress and share all the information for a richer experience.

**Comment by rfm-targa** [comment]
Hello @artmisk13 and @hkaspersen,

We have just released chewBBACA v3.2.0. This version includes a new version of the SchemaEvaluator module. You can read the [Changelog](https://github.com/B-UMMI/chewBBACA/blob/master/CHANGELOG.md) to know what is new in the latest version. We have also updated the [docs page](https://chewbbaca.readthedocs.io/en/latest/user/modules/SchemaEvaluator.html) about the SchemaEvaluator module. You can install v3.2.0 through [pip](https://pypi.org/project/chewBBACA/) or [conda](https://anaconda.org/bioconda/chewbbaca/files). Let us know if you try the new SchemaEvaluator. We would appreciate any feedback.

Kind regards,

Rafael

**Comment by artmisk13** [comment]
Hi @rfm-targa,

Thank you very much for letting me know. I have just used updated my chewbbaca to v3.2.0 via conda and re-tried the schema evaluator. However, it gave me a new error as follows: 
<img width="1369" alt="image" src="https://github.com/B-UMMI/chewBBACA/assets/99484530/10dcba95-372e-49aa-955e-d9d710b2cbf8">

Can you please assist with this problem?

Many thanks,
Krisna

**Comment by rfm-targa** [comment]
Hi @artmisk13,

Great to know that you've found a solution to the issue. Let me know if you find any bugs or have feature requests for the SchemaEvaluator module.

Best regards,

Rafael
