### ISSUE TITLE
FileNotFound error

### ISSUE THREAD

**Issue by johnlees** [B-UMMI/chewBBACA#16]
Hi,

I am running chewBBACA version 2.0.12 (installed through conda), and am getting an error with `AlleleCalli` mode. I have downloaded the cgMLST scheme for *Listeria monocytogenes* from https://www.cgmlst.org/ncs, which I then ran `PrepExternalSchema` on, which completed successfully. I see that there are directories `short` and `temp` in the schema folder.

However when running the command:
```
chewBBACA.py AlleleCall -i listeria_assemblies -g listeria_cgmlst -o listeria_chewbbaca --cpu 1 --ptf Listeria_monocytogenes.trn -v --fr
```
It fails, with the following error:
```
Finished Allele Calling at : 21:06:44-17/09/2018
Wrapping up the results
[Errno 2] No such file or directory: '/lustre/scratch118/infgen/team81/jl11/pdoc/assigning/revisions/listeria_cgmlst/temp/lmo0001.fasta_result.txt'

        USAGE : chewBBACA.py [module] -h

Select one of the following functions :

CreateSchema : Create a gene by gene schema based on genomes
AlleleCall : Perform allele call for target genomes
SchemaEvaluator : Tool that builds an html output to better navigate/visualize your schema
TestGenomeQuality : Analyze your allele call output to refine schemas
ExtractCgMLST : Select a subset of loci without missing data (to be used as PHYLOViZ input)
RemoveGenes : Remove a provided list of loci from your allele call output
PrepExternalSchema : prepare an external schema to be used by chewBBACA
JoinProfiles : join two profiles in a single profile file
UniprotFinder : get info about a schema created with chewBBACA
```

The directory noted does exist, and contains three types of file (a single example of each, but looks like they are there for every gene and isolate):
```
lmo0901.fasta_argList.txt
19183_4#78.contigs_velvet.fa
19183_4#78.contigs_velvet.fa_ORF.txt
```

Any help much appreciated!

**Comment by mickaelsilva** [comment]
hello John, 

I would re-run the PrepExternalSchema step, since that "temp" folder should not be in the schema folder if the run was sucessful. The schema folder should only have one fasta file per locus. After PrepExternalSchema  is sucessfull, there should be only the fasta files you provided and a short folder, each with 2 files per locus.

Let me now if the re-run of PrepExternalSchema went this way.

**Comment by johnlees** [comment]
Thanks for the quick reply! The `PrepExternalSchema` step looks ok -- I have the folders you suggested containing the correct number of files (I realise the `temp` folder was only create by the subsequent run of `AlleleCall`)

**Comment by mickaelsilva** [comment]
Ok that is expected then. I would bet something is odd with one of your genomes. Re-try with a single genome file, you can also try to run dos2unix on the genomes sometimes there are some dos encoding that messes with the program. You can also take a look at the lmo0001.fasta locus and see if nothing is odd on it.

**Comment by johnlees** [comment]
Hmm, I'm still getting the error on a single example (I think the genome assemblies are ok, they've been used for many other things before). Can't find anything obviously odd in the locus fasta files, other than an extra newline between alleles -- is that a problem? Couldn't find any DOS line endings either

`lmo0001.fasta`:
```
>1
GTGCAATCAATTGAAGACATCTGGCAGGAAACACTGCAAATTGTTAAAAAAAATATGAGTAAACCTAGTTACGATACATGGATGAAATCAACAACCGCTCATTCACTTGAAGGTAACACGTTTATTATTTCAGCGCCCAATAATTTTGTTCGCGATTGGTTAGAGAAAAGCTACAC
TCAATTTATCGCTAACATTTTGCAAGAAATAACTGGTCGCTTATTTGATGTCCGCTTTATTGATGGCGAGCAGGAAGAAAACTTTGAATACACTGTGATTAAACCAAATCCAGCATTAGATGAAGATGGCATTGAAATTGGAAAACATATGCTTAATCCACGTTATGTTTTTGATA
CCTTTGTCATTGGTTCAGGGAACAGATTTGCCCACGCAGCATCACTTGCAGTAGCCGAAGCACCAGCGAAAGCATATAATCCACTCTTCATTTATGGAGGAGTTGGCCTCGGTAAAACACATTTAATGCACGCAGTTGGCCACTATGTTCAACAACATAAAGATAATGCGAAAGTA
ATGTACCTTTCCAGCGAAAAATTCACCAATGAGTTTATTAGCTCTATTCGTGATAATAAAACCGAAGAATTTCGCACAAAATATCGGAATGTTGATGTCTTACTTATTGATGATATTCAATTTTTAGCCGGTAAAGAAGGAACACAAGAGGAATTTTTCCATACATTTAACACACT
TTATGATGAACAAAAGCAAATTATTATTTCCAGTGACCGACCACCAAAAGAAATTCCTACACTGGAAGATCGACTGAGATCCCGCTTTGAATGGGGCTTAATTACTGATATTACGCCACCAGACTTAGAAACCCGGATCGCCATTTTACGTAAAAAAGCAAAAGCAGACGGATTAG
ATATTCCAAATGAAGTTATGCTTTATATCGCAAACCAAATTGATTCGAATATTCGCGAGCTAGAAGGCGCTCTCATCCGAGTAGTTGCTTATTCTTCCCTCGTTAATAAAGATATAACAGCTGGTCTTGCAGCAGAAGCACTAAAAGATATTATCCCCTCTTCTAAATCACAAGTT
ATTACTATTAGTGGTATTCAAGAAGCAGTCGGTGAATATTTCCACGTTCGTTTAGAAGATTTTAAAGCAAAAAAACGGACGAAAAGTATAGCATTCCCGCGCCAAATCGCCATGTATCTCTCAAGAGAGCTTACAGATGCCTCATTACCAAAAATCGGTGATGAATTTGGTGGTCG
AGATCATACAACAGTTATTCATGCACATGAAAAAATATCGCAACTACTAAAAACCGATCAAGTGTTGAAAAATGACCTTGCCGAAATTGAAAAAAATTTAAGAAAAGCACAAAATATGTTTTAA

>2
GTGCAATCAATTGAAGACATCTGGCAGGAAACACTGCAAATCGTTAAAAAAAATATGAGTAAACCTAGTTACGACACATGGATGAAATCAACAACCGCTCATTCACTTGAAGGTAACACGTTTATTATTTCAGCGCCCAATAATTTTGTTCGCGATTGGTTAGAGAAGAGTTACAC
GCAATTTATCGCTAACATTTTGCAAGAAATAACTGGTCGCTTATTTGATGTCCGCTTTATTGATGGCGAGCAGGAAGAAAACTTTGAATACACTGTGATTAAACCAAATCCAGCGTTAGATGAAGATGGCATTGAAATTGGAAAACATATGCTTAATCCGCGTTATGTTTTTGATA
CTTTTGTCATTGGTTCAGGGAACAGATTTGCCCACGCAGCATCACTTGCAGTAGCCGAAGCACCAGCGAAAGCATATAATCCACTCTTCATTTATGGAGGAGTTGGCCTCGGTAAAACACATTTAATGCACGCAGTTGGCCACTATGTTCAACAACATAAAGATAATGCGAAAGTA
ATGTACCTTTCCAGCGAAAAATTCACCAATGAGTTTATTAGCTCTATTCGTGATAATAAAACCGAAGAATTCCGTACAAAATACCGGAATGTGGATGTCTTACTTATTGATGATATTCAATTTTTAGCAGGTAAAGAAGGAACACAAGAGGAATTTTTCCATACATTTAACACACT
TTATGATGAACAAAAGCAAATTATTATTTCCAGTGACCGACCACCGAAAGAAATTCCAACATTGGAAGATCGACTGAGATCCCGCTTTGAATGGGGCCTAATTACTGATATTACGCCACCAGACTTAGAAACACGGATCGCCATTTTACGTAAAAAAGCAAAAGCAGACGGATTAG
ATATTCCAAATGAAGTCATGCTTTACATCGCAAACCAAATTGATTCGAATATTCGCGAGCTAGAAGGCGCACTCATCCGAGTAGTTGCTTATTCTTCCCTCGTTAATAAAGATATAACAGCTGGTCTTGCAGCAGAAGCACTAAAAGATATTATCCCCTCTTCTAAATCACAAGTT
ATTACAATTAGTGGTATTCAAGAAGCAGTCGGTGAATATTTCCATGTTCGTTTAGAAGATTTTAAAGCAAAAAAACGGACGAAAAGTATCGCATTCCCGCGCCAAATCGCTATGTATCTTTCAAGAGAGCTTACAGATGCCTCATTACCAAAAATCGGTGATGAATTTGGTGGTCG
AGATCATACAACCGTCATCCATGCACATGAAAAAATATCGCAACTACTAAAAACCGATCAAGTGTTGAAAAATGACCTTGCCGAAATTGAAAAAAATTTAAGAAAAGCACAAAATATGTTTTAA
```

**Comment by johnlees** [comment]
Looking at little higher up the log:
```
starting allele call blast at: 21:47:11-17/09/2018
/lustre/scratch118/infgen/team81/jl11/pdoc/assigning/revisions/listeria_single/19183_4#48.contigs_velvet.fa
Finished Allele Calling at : 21:47:11-17/09/2018
```
Is this a suspiciously short time (I think it was immediate)? Is the allele call blast step failing?

**Comment by mickaelsilva** [comment]
Probably, can you try to rename the extension of the genome to .fasta? Maybe the biopython parser has issues with the .fa extension.. 

If that doesn't work, could ou email-me the genome so I can check tomorrow morning what is the issue?

**Comment by johnlees** [comment]
I am also not getting the verbose messages in `callAlleles_protein3.py` despite having the flag on (assuming that's the function being called)

**Comment by johnlees** [comment]
No luck renaming the extension, I'll email you the genome now. Thanks for the help!

**Comment by jacarrico** [comment]
@johnlees we just ran analysis today (@ODiogoSilva did) with the same schema and we managed to do it. I will ping you on Slack tomorrow morning to try to sort this out with you and @mickaelsilva !

**Comment by johnlees** [comment]
Great, thanks all. I am perhaps wondering if it's a problem with my
environment/blast executable. I will try with a clean environment tomorrow,
unless there's something else you find I got wrong before then

**Comment by johnlees** [comment]
This was caused by prodigal failing with a segfault
```
prodigal -i /lustre/scratch118/infgen/team81/jl11/pdoc/assigning/revisions/listeria_single/19183_4\#48.contigs_velvet.fa -c -m -g 11 -p single -f sco -t /lustre/scratch118/infgen/team81/jl11/pdoc/assigning/revisions/Listeria_monocytogenes.trn
-------------------------------------
PRODIGAL v2.60 [October, 2011]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.
-------------------------------------
Reading in training data from file /lustre/scratch118/infgen/team81/jl11/pdoc/assigning/revisions/Listeria_monocytogenes.trn...done!
-------------------------------------
Request:  Single Genome, Phase:  Gene Finding
Finding genes in sequence #1 (1530263 bp)...[1]    28512 segmentation fault  prodigal -i  -c -m -g 11 -p single -f sco -t
```

Updating prodigal to v2.6.0 fixed this error
