### ISSUE TITLE
Training files

### ISSUE THREAD

**Issue by lskatz** [B-UMMI/chewBBACA#17]
Hi, I am writing a suggestion that you add training files to the ChewBBACA repository.  First, it will help users stay consistent between runs.  Second, your centralized training files will help us stay consistent between laboratories.  Third, these files seem to be well thought out and would help control for any user errors.  https://github.com/mickaelsilva/prodigal_training_files

**Comment by mickaelsilva** [comment]
Prodigal training files are now included on the package. After uploading to 2.0.15 you should now be able to use for instance:

 `--ptf  Acinetobacter_baumannii.trn`
