### ISSUE TITLE
If the input is the eukaryotic group, how can I get the training file?

### ISSUE THREAD

**Issue by alienn233** [B-UMMI/chewBBACA#170]

**Comment by ramirma** [comment]
Dear @alienn233,
Thank you for your interest in chewBBACA. Unfortunately the current version of chewBBACA will not work directly with eukaryotic genomes. Prodigal, which is used in the initial steps of chewBBACA, is specifically designed to detect prokaryotic coding sequences and it will not work properly in a eukaryotic genome. However, you can [create a schema using only coding sequences](https://chewbbaca.readthedocs.io/en/latest/user/getting_started/quick_start.html#option-2-coding-sequences) and perform allele calling also [using only coding sequences](https://chewbbaca.readthedocs.io/en/latest/user/getting_started/quick_start.html#perform-allele-calling). To do this, you need to provide a single fasta file for each strain, containing all that strain's coding sequences. We are currently considering developing an integrated solution but at this time this is the only option.
