### ISSUE TITLE
()join error str or byte not boolean when running chewBBACA 2.0.15

### ISSUE THREAD

**Issue by kristyhoran** [B-UMMI/chewBBACA#18]
@jacarrico and @mickaelsilva  We have updated to version 2.0.15 and a previously fine command `chewBBACA.py AlleleCall -i assemblies/ -g path/to/genomes -o outputdir --cpu 36` for calling alleles causes the following error `join() argument must be str or bytes, not 'bool'`. I have tried the installation on our server and also your docker container with the same result... I have version 2.0.12 in a singularity container and it works just fine. I have not been able to find the problem.... Any help would be greatly appreciated!! Thanks heaps in advance. Cheers Kristy

**Comment by jacarrico** [comment]
Hi @kristyhoran ...hmm seems that some weird bug has crept in 2.0.15. Have you tried with just one assembly to check if it is the fault of one specific assembly? 
@mickaelsilva can you have a look at this

**Comment by mickaelsilva** [comment]
Might be the lack of training file, I'll look into it.

**Comment by jacarrico** [comment]
Thanks @mickaelsilva! @kristyhoran we highly recommend using a training file , as without it some assemblies can lead to lots of different calls due to wrong cds assignment

**Comment by kristyhoran** [comment]
@mickaelsilva @jacarrico thanks for the quick fix and the advice!!
