### ISSUE TITLE
Did the arg `--fr` get dropped?

### ISSUE THREAD

**Issue by russellsmithies** [B-UMMI/chewBBACA#180]
We're trying to run Coreugate but it's failing at the chewie stages with what looks like an invalid argument.  Did the `--fr` arg get dropped at some point?  This is what I'm seeing:
```Perform allele calling with FASTA files that contain CDS:
  chewBBACA.py AlleleCall -i <input_files> -g <schema_directory>-o <output_directory> --cds
AlleleCall: error: unrecognized arguments: --fr

chewBBACA version: 3.2.0
Authors: Rafael Mamede, Pedro Cerqueira, Mickael Silva, João Carriço, Mário Ramirez
Github: https://github.com/B-UMMI/chewBBACA
Documentation: https://chewbbaca.readthedocs.io/en/latest/index.html
Contacts: imm-bioinfo@medicina.ulisboa.pt
```
thanx,

**Comment by rfm-targa** [comment]
Greetings @russellsmithies,

The `--fr` parameter was removed in version 3.0.0. That version included a new implementation of the AlleleCall module and the `--fr` parameter was not implemented for that version. Version 3 generates very similar results to version 2, but it is much faster and works quite differently under the hood. The `--fr` parameter would not work well with the temporary and results file structure we adopted for the latest versions. The current behaviour is to create the output folder if it does not exist and to create a subfolder inside the output folder if it already exists (creates a subfolder named `results_<datestamp>` to store all the files and avoid mixing files with anything that was already in the output file).

Best regards,

Rafael

**Comment by russellsmithies** [comment]
Thanx @rfm-targa 
I read back thru the release notes and spotted it was dropped in v3.0.0 so a simple tweak to the installed version in coreugate got it working.  
If you're interested, https://github.com/kristyhoran/Coreugate/issues/5

**Comment by russellsmithies** [comment]
Thanx @rfm-targa 
I read back thru the release notes and spotted it was dropped in v3.0.0 so a simple tweak to the installed version in coreugate got it working.  
If you're interested, https://github.com/kristyhoran/Coreugate/issues/5

**Comment by rfm-targa** [comment]
Thank you for the feedback, @russellsmithies.
