### ISSUE TITLE
Newest Pyrodigal breaks chewBBACA

### ISSUE THREAD

**Issue by karlkashofer** [B-UMMI/chewBBACA#185]
Pyrodigal 3.0.0 alpha has a breaking change:
`BREAKING: Rename OrfFinder to GeneFinder for consistency.`

https://github.com/althonos/pyrodigal/releases/tag/v3.0.0-alpha1

This breaks chewBBACA when built from your very convenient dockerfile.
`pyrodigal.OrfFinder(training_info=training_data,
AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'`

quick solution is to force the pyrodigal version to be <3
`sed -i 's/pyrodigal>=2.2.0/pyrodigal>=2.2.0,<3/g' setup.py`

Cheers,
KK & SS

**Comment by rfm-targa** [comment]
Hello @karlkashofer,

Thank you for reporting this issue. Pyrodigal v3 is still in an alpha release, so we will change the requirements in chewBBACA v3.3.0 to >=2.2.0, <=2.3.0. We will adapt the code to work with Pyrodigal v3 when there is a stable release.

Best regards,

Rafael

**Comment by rfm-targa** [comment]
Hello @karlkashofer,

We've released chewBBACA v3.3.0. This version supports pyrodigal>=3.0.0.
Once again, thank you for reporting this issue.
I'll close this issue, but let us know if you find any issues in the latest version.

Best regards,

Rafael
