### ISSUE TITLE
Create git tag for v3.2.0 release

### ISSUE THREAD

**Issue by alanorth** [B-UMMI/chewBBACA#188]
Hey there, we are using chewBBACA v3.2.0 from pypi.org (pip install), but I notice there is no git tag in the repository for that release. Could you please create one?

Thank you!

**Comment by rfm-targa** [comment]
Hello @alanorth,

Thank you for your interest. I created a [release](https://github.com/B-UMMI/chewBBACA/releases/tag/v3.2.0) for version 3.2.0. Please let us know if it matches what you requested.

Kind regards,

Rafael

**Comment by alanorth** [comment]
This is perfect, even better than I expected. Thanks!
