### ISSUE TITLE
Coding strand convention

### ISSUE THREAD

**Issue by a-damC** [B-UMMI/chewBBACA#193]
Hello,

I am looking at the cds_coordinates.tsv and results_contigsInfo.tsv output from chewBBACA.

I am unfamiliar with the coding strand convention of 0 & 1 and a google search did not produce any conclusive results.

Is 0 the + (forward) strand or is it the - (reverse) strand?

Thank you,
Adam

**Comment by rfm-targa** [comment]
Hello @a-damC,

chewBBACA <3.3.0 used `1` for the forward strand and `0` for the reverse strand.
This has changed for chewBBACA >3.3.0, which  uses the strand values assigned by Pyrodigal, `1` for the forward strand and `-1` for the reverse strand. We recommend updating chewBBACA if you are not using the latest version.
Thank you for opening this issue. We noticed that the docs do not include information about the strand values. We will update the docs soon.

Kind regards,

Rafael

**Comment by rfm-targa** [comment]
Hello @a-damC,

We updated the documentation pages for the CreateSchema and AlleleCall modules with information about the coding strand convention (included in the description of the `cds_coordinates.tsv` output file, [here](https://chewbbaca.readthedocs.io/en/latest/user/modules/CreateSchema.html#outputs) and [here](https://chewbbaca.readthedocs.io/en/latest/user/modules/AlleleCall.html#outputs)).
I am closing this issue, but let us know if there is anything else.

Kind regards,

Rafael
