### ISSUE TITLE
No usable gene files in listGenes2Call.txt

### ISSUE THREAD

**Issue by MNNatUA** [B-UMMI/chewBBACA#20]
Hello, I'm a newbie and I’m encountering an error with ChewBBACA while doing allele calling.

Following are the command lines I used:

########Create Schema
`chewBBACA.py CreateSchema -i /home/Consensus/ --cpu 4 -o /home/Chewbbaca-Results --ptf /home/chewBBACA/CHEWBBACA/prodigal_training_files/Escherichia_coli.trn` 

---> Outputs include: folder /home/temp/, with 374 sub-folders of protogenomes and ORF.txt files for all the genomes; listGenes2Call.txt (0 bytes) and listGenomes2Call.txt (26.7kb) in /home/ChewBBACA/CHEWBBACA/

####### Allele Call
`chewBBACA.py AlleleCall -i /home/Consensus/ -g /home/temp/ --cpu 4 -o /home/Saturn-Chewbbaca-Results --ptf /home/chewBBACA/CHEWBBACA/prodigal_training_files/Escherichia_coli.trn` 

> chewBBACA version 2.0.16 by Mickael Silva at https://github.com/B-UMMI/chewBBACA
> email contact: mickaelsilva@medicina.ulisboa.pt
> 
> 
> 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> ...
> 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> will use this training file : /home/chewBBACA/CHEWBBACA/prodigal_training_files/Escherichia_coli.trn
> blastp
> Will use this number of cpus: 4
> Checking all programs are installed
> Checking Blast installed... True
> Checking Prodigal installed... True
> blast version is up to date, the program will continue
> 
> Starting Script at : 11:10:01-09/01/2019
> checking if genome files exist..
> checking if gene files exist..
> ERROR! No usable gene files in listGenes2Call.txt

This file listGenes2Call.txt is indeed 0 byte in size. But I dont know why this happened.

Any help is appreciated.

**Comment by jacarrico** [comment]
Hi. Thanks for the contact! 
What is the contents of `/home/Consensus/ `?

**Comment by MNNatUA** [comment]
Dear,

I have contacted Mickael Santos da Silvaand and have received suggestions to fix the problem.
Many thanks for following up the post.

Best regards,

**Comment by TheBready** [comment]
Hi, I have the same issue. What was the solution to your problem?
Best regards

**Comment by jacarrico** [comment]
@mickaelsilva or @MNNatUA Could you help @TheBready please?

**Comment by mickaelsilva** [comment]
> The first step of creating the schema didn't work as expected. The output from should be a single folder, in your case "Chewbbaca-Results" (also advised to use "_" instead of "-" in file names . Maybe there was a problem with the files inside your "Consensus" folder. Be sure that inside that folder there is only fasta files of genomes.

> You can first try to create a schema with a complete genome or a single genome file of your preference, then if it works try a new schema creation with your files.

This was the reply to the original poster, let me know if it helped @TheBready
