### ISSUE TITLE
Can I get STs with cgMLST? (cgST)

### ISSUE THREAD

**Issue by juanjo255** [B-UMMI/chewBBACA#208]
Hello @rfm-targa,

Is there a way to get the ST from cgMLST as with MLST? Can you help me understand why its common to get notation from MLST but not from cgMLST?

Thank you for the help,

Juan

**Comment by ramirma** [comment]
Hi @juanjo255 ,

Thank you for your interest in chewBBACA.  The difficulty in obtaining a unique identifier from a genome based MLST method is the potential missing data (i.e. loci which are in the schema but not present in all isolates). If we consider a strict cgMLST, i.e. including loci present in 100% of the strains this could be overcome, but we would probably end up with a much reduced number of loci. If we consider the dataset in question and not the entire species, the cgMLST will be much larger and discriminant but any ST-like identifiers will not be applicable in other contexts.

**Comment by juanjo255** [comment]
Dr. @ramirma ,

It was very clear. 

Thank you very much for the explanation,

Juan
