### ISSUE TITLE
Where to prodigal training files come from?

### ISSUE THREAD

**Issue by karinlag** [B-UMMI/chewBBACA#21]
Hi!

I'd like to use this for a new species, for which there is no prodigal training file. How or where do I go about procuring or producing one?

Thanks!

**Comment by cimendes** [comment]
Hello!

You can produce a new training file with a reference complete genome using the command:
`prodigal -i <reference>.fna -t <output_training_file>.trn -p single`

I hope it helps. :)

**Comment by mickaelsilva** [comment]
@cimendes is correct, thanks cimendes.

See https://github.com/B-UMMI/chewBBACA#q-my-favorite-species-has-no-training-file-what-can-i-do

**Comment by mickaelsilva** [comment]
Which kind of result from prokka would you want to use? I think prokka uses prodigal on the back to get the CDS hence I would expect the results to be the same.

**Comment by jacarrico** [comment]
You could eventually use prokka results if you used the same prodigal training file for the schema . Not sure if prokka supports that. I will ask Torsten.

**Comment by elina2410** [comment]
In command: 
prodigal -i <reference>.fna -t <output_training_file>.trn -p single

what genome as **-i <reference>.fna** should I chose? Genome which was used as the “seed genome” for the cgMLST scheme definition?
I downloaded a cgMLST scheme but there is no training file for this organism.

**Comment by rfm-targa** [comment]
Hello @elina2410,

What we usually do is get a reference genome for the species and use that genome to create the training file. If you're working with a schema developed based on a specific lineage, you can use the genome of a strain representative of that lineage. You can also concatenate the FASTA files of several genomes and pass that to Prodigal.

Kind regards,

Rafael

**Comment by ramirma** [comment]
Just a note to complement Rafael's answer. If you downloaded a schema from [chewie-NS](https://chewbbaca.online/), then the schema should have come with a training file. Do let us know if this was not the case. We make some training files available in [chewBBACA's website](https://github.com/B-UMMI/chewBBACA/tree/master/CHEWBBACA/prodigal_training_files) too. Hope this helps.

**Comment by elina2410** [comment]
Hi  @rfm-targa @ramirma 
I downloaded schema from: https://www.cgmlst.org/ncs/schema/3884856/
So it is not schema form chewie-NS.
I adapted this external schema to be used with chewBBACA but without using any prodigal training file... I would like to produce one for this schema and perform adaptation again with created prodigal training file as it is recommended.

**Comment by ramirma** [comment]
Dear @elina2410 ,
We would indeed advise you to use a training file for more consistent allele calls. You can find instructions on how to do that in [prodigal's website](https://github.com/hyattpd/prodigal/wiki/Gene-Prediction-Modes#training-mode). As for the choice of strain it is really up to you. One possibility would be to use the genome of the strain used to create the schema (NC_017316.1) or you could use another high quality closed genome.
I hope to have clarified your question.
Mario

**Comment by elina2410** [comment]
Yes, I took the strain used to create the schema - NC_017316.1. 
Thank you for your assistance. 
Best,
Ewelina
