### ISSUE TITLE
100% blast hit with allele but different allele is called or other output(LNF/ASM/ALM/NIPH)

### ISSUE THREAD

**Issue by moorembioinfo** [B-UMMI/chewBBACA#22]
Hi! 

I've just started using chewBBACA so I could be missing something here but I can't tell what at the moment. The issue I'm having is that I'm using an external scheme for C. difficile and it's calling the reference genome alleles wrong. All of the geneX_1 alleles are from the reference genome (https://jcm.asm.org/content/56/6/e01987-17/figures-only) and as such all the alleles called should be 1. 

Instead, most are 1, but there's also 216 that are a combination of different profiles and even loci not found. I blasted all these alleles against the reference and they were all present 100%. 

Here's what I did:

- Create training file

prodigal -i R00000003.fna -p train -t R00000003.fasta.trn
This training file is used later during allele calling

- Prep external schema

chewBBACA.py PrepExternalSchema -i ~/scheme_fastas/ --cpu 16

With the C. difficile scheme from cgMLST.org (https://www.cgmlst.org/ncs/schema/3560802/) and fasta headers (already numbered) edited to include gene name (>genename_number)

- Call alleles with reference genome (isolate 630/R00000003.fasta)

chewBBACA.py AlleleCall -i ~/paper_genomes_samples/ -g ~/scheme_fastas/ -o results_cg --cpu 12 --ptf ~/630_prodigal_training/R00000003.fasta.trn

Which provides this allele call output:

R00000003.fasta,1,1,1,1,1,1,1,1,34,1,1,55,1,1,1,1,1,1,1,1,1,1,41,1,1,1,1,1,1,1,83,1,1,1,1,40,1,1,1,1,1,1,1,1,1,1,1,1,69,1,40,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,45,1,1,1,1,1,1,1,1,18,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,60,1,1,1,1,1,LNF,1,1,1,1,1,1,1,1,1,104,1,1,1,1,1,43,1,1,1,1,197,1,1,1,1,1,1,1,1,1,128,1,1,60,1,1,1,1,1,1,82,1,1,1,75,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,97,1,1,1,1,1,1,1,1,1,1,53,1,1,1,1,1,96,1,1,1,1,1,1,1,1,1,75,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,193,1,1,1,1,1,178,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,225,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,ALM,1,1,1,1,1,1,1,1,1,1,115,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NIPH,1,1,1,1,123,1,1,1,1,1,1,42,1,1,124,1,1,1,1,1,92,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,92,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,99,1,1,195,1,1,1,1,150,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,107,1,150,1,1,128,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,98,1,1,1,1,1,1,1,1,1,1,1,1,119,1,1,1,1,80,1,1,1,1,1,1,1,1,1,177,1,1,1,1,1,1,1,1,1,1,1,192,1,117,1,1,1,1,1,1,1,1,1,1,54,1,1,1,1,1,1,1,1,1,163,1,1,1,1,1,146,1,1,1,1,1,85,1,1,1,1,1,1,1,1,1,135,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,64,1,113,1,102,1,1,1,1,1,1,1,1,1,1,1,1,1,1,72,1,1,1,1,1,1,1,1,1,1,1,1,1,1,147,1,1,1,1,1,1,74,1,1,1,77,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,57,1,1,1,85,1,1,1,1,1,1,1,1,1,1,1,1,1,34,1,1,1,1,1,121,1,1,1,1,1,1,1,1,1,1,1,1,93,1,1,141,1,1,1,1,1,1,1,1,1,1,146,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,94,1,1,1,1,1,1,1,1,1,1,1,1,91,1,1,1,1,1,1,1,119,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,LNF,1,1,1,1,1,1,1,1,1,1,1,105,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,47,1,1,1,1,1,1,1,1,1,1,1,ALM,1,1,1,LNF,1,1,169,1,1,1,1,1,1,96,1,1,1,1,1,1,1,156,1,1,90,1,1,1,1,1,1,1,1,42,1,26,1,1,1,1,1,1,1,1,95,1,1,67,1,1,99,1,1,1,1,164,1,1,148,1,1,1,1,94,1,1,1,36,1,1,1,1,1,1,1,283,1,1,1,1,1,75,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,116,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,205,1,1,1,1,1,1,1,1,1,1,1,150,1,1,1,1,1,1,1,1,1,1,1,1,1,119,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,68,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,84,1,1,1,1,1,1,1,1,1,1,96,1,1,1,1,1,1,54,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,LNF,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,103,1,1,1,1,1,1,86,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,LNF,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,116,1,1,1,1,1,1,1,1,1,99,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,145,1,1,1,1,1,1,1,107,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,52,1,68,1,1,1,1,1,1,62,1,1,1,1,68,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,ASM,1,1,1,37,1,1,1,1,72,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,120,1,1,1,1,1,1,1,1,1,103,1,1,1,1,1,1,1,1,1,1,1,1,1,128,102,1,1,108,1,177,243,1,1,1,1,1,1,1,99,1,1,1,1,1,1,1,45,1,1,1,135,1,1,1,1,1,100,92,186,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,95,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,242,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,132,1,1,1,1,1,1,1,ALM,1,1,LNF,1,1,1,1,1,1,28,1,93,1,1,160,1,1,1,99,1,1,1,1,1,170,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,41,1,59,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,89,1,1,1,1,97,20,1,1,1,1,1,1,1,1,1,1,1,LNF,1,1,1,1,1,1,150,1,1,1,1,1,108,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,160,1,1,1,138,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,144,1,1,1,1,1,1,1,1,150,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,103,1,1,1,1,190,1,1,1,1,76,1,1,1,1,1,116,1,1,118,1,1,1,1,1,90,1,1,1,1,1,1,1,1,1,1,81,99,1,1,65,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,83,176,68,1,1,1,1,1,1,1,1,1,1,1,1,1,1,207,1,1,1,1,1,86,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,53,1,1,1,221,1,1,1,1,1,1,1,1,LNF,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,89,1,1,1,1,1,1,99,1,1,1,1,1,1,1,1,NIPH,213,1,1,1,1,NIPH,1,1,43,1,1,1,1,1,1,1,1,1,187,1,1,1,1,1,LNF,1,1,1,107,1,1,1,NIPH,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NIPH,1,1,1,1,1,1,1,1,135,1,1,1,1,1,1,1,1,1,124,1,1,1,1,1,1,1,1,1,1,1,1,1,1,68,1,1,1,1,1,1,1,176,1,1,1,1,1,1,NIPH,1,1,70,1,1,1,1,1,1,123,165,1,1,1,1,1,1,1,1,1,1,1,1,LNF,1,1,1,1,1,173,1,1,1,174,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,158,180,1,1,1,1,1,1,1,1,1,1,LNF,1,1,1,1,1,1,1,1,LNF,1,1,1,1,1,1,1,1,1,1,15,1,1,1,1,1,1,1,1,1,1,1,1,90,1,1,1,1,1,1,1,1,1,60,1,1,1,1,1,1,1,1,1,1,1,122,1,ALM,100,1,1,1,1,1,1,1,1,1,1,LNF,1,1,1,1,1,66,1,131,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,127,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,125,1,1,1,1,1,1,1,1,1,1,1,1,1,92,1,1,98,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,56,1,1,1,1,1,1,1,1,1,1,ASM,1,1,1,1,1,1,114,1,1,1,1,1,51,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,62,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,113,1,50,1,1,1,61,1,1,105,1,108,1,1,1,1,1,1,1,142,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,ALM,1,1

__________________

The output should be 1 for every allele according to the original scheme development paper. I checked this with blast and all allele 1 sequences are 100% present in the reference (no gaps, no mismatches etc.)

Is this an issue with chewBBACA, the training file, the difference between chewBBACA and seqsphere (used to generate the scheme) or am I missing something?

**Comment by jacarrico** [comment]
Hi 
I suspect the difference you find problem is that Seqsphere and chewBBACA have different ways to call alleles with the major difference being on the definition if the locus by prodigal done in chewBBACA. This is because that the start codon can be different from the ones defined in Seqsphere. In Seqsphere they also have lots of restrictions in allele length for a given locus. 
What I find strange is if the alleles have a number that number is from the seqsphere right? 

is R00000003.fna  available and a complete genome? or a draft assembly? 
I would create the training file from a complete genome and try again the allele call.  If it is a draft genome that is quite fragmented might be introducing a bad CDS prediction in prodigal.

Also I would explore exactly what are the differences in the allele called . I am quite curious to see that. Check if there are alleles that are larger than others. For instance in the locus 9 you have allele 34. What is the the difference with allele 1?

Let me know what you find. We do vouch that the allele calls with chewBBACA using the same database and training file are quite reproducible.

**Comment by mickaelsilva** [comment]
@jacarrico is correct. Also you can use the -v flag to get the blast matches on the stdout and try to investigate the specific case for each different locus.

I would bet those differences are the result of the different approaches on the gene sequence detections/ CDS that seqsphere and chewbbaca use. With chewbbaca we pass that burden to prodigal, either on allele call and schema creation, with the suggestion of usage of a common training file for the best possible congruent result for all strains of that specific species.

**Comment by moorembioinfo** [comment]
Hi @jacarrico, thanks so much for the response and @mickaelsilva thanks also for your response, I’ll re-run now with the -v flag that should be helpful. I'm still looking at the data but it does seem there are a few issues with the scheme. R00000003.fna/isolate 630 is a complete genome and was the seed genome for the scheme and in the original study. 

For instance I've looked at locus 9 and it’s the case that allele 1 and 34 are the same except for ATGTCT prepended to allele 34 (allele one starts with a start codon —the full sequence is below with the additional start for allele 34 in bold). 

**ATGTCT**ATGAATATTGATTCAAATTTAGATTCACAAAATAAATTTTGGAATGTTTGTCTTGATGGAGAACTTGATGTTTCTACAGCAGATAAACTAAAGGAACATTTACATGCTTTAATAGAAAAAAATATGTTAGATGTAAAGATTAATCTTAAAGATTTAGATTATATAGACTCAACAGGCTTAGGAGCTATGATAGGTGTATTAAAAAAATTAAAAATAAATGAAAAAGAGATATACATAGTAAATCCTAAGAGTAACGTAAGAAAGATTTTTACTATAACAGGTCTAGATAAAATATTTAAAGTGGAGGGATAA

It's the case that for 221 loci there are alleles that are subsets of other alleles that in some cases are both present in the reference. I wonder how chewBBACA makes the decision to assign one or the other though? Perhaps it should give an error if it can just as easily be one or the other?

I can't work out the issue with the LNF loci, there are 13 altogether and these all yield a 100% blast hit (as they should). (Perhaps running with the -v flag will shine some light on this)

**Comment by jacarrico** [comment]
Hello @moorembioinfo . Thank you for the follow-up. 

> It's the case that for 221 loci there are alleles that are subsets of other alleles that in some cases are both present in the reference. I wonder how chewBBACA makes the decision to assign one or the other though? Perhaps it should give an error if it can just as easily be one or the other?
Ok that is good news (at least as we interpret them). chewBBACA doesn't  do the selection directly. Remember that the genome is converted into CDS with prodigal and it is prodigal that chooses the largest reading frame in those cases. If you create the schema from scratch with chewBBACA you usually don't run into that problem. In those cases we would always keep the largest allele and therefore the others would never appear in the allele call. 

> I can't work out the issue with the LNF loci, there are 13 altogether and these all yield a 100% blast hit (as they should). (Perhaps running with the -v flag will shine some light on this)

Please do and let us know what happens. This is quite odd. What are the length of those  loci?

**Comment by moorembioinfo** [comment]
Yeah the various loci where the wrong allele is called are all subsets of one another allele in that profile (so not chewBBACAs fault), I'll contact the scheme curators about this. The ASM/ALM/NIPH are a little harder to scrutinise but these again should be issues with the scheme and not chewBBACA. 

I'll let you know what I can work out about the LNF loci! :)

**Comment by mickaelsilva** [comment]
Truth is we don't know which allele sequence is the good one, ours or the external scheme you are using . However, since we always use prodigal in chewbbaca, at least we can be sure to be doing the same "error"in every run, unlike other manual curations.

**Comment by jacarrico** [comment]
> The ASM/ALM/NIPH are a little harder to scrutinise but these again should be issues with the scheme and not chewBBACA.

ASM and ALM are usually found if the schema alleles are consistently 20% larger or 20% smaller than the alleles found in Prodigal. NIPH are the ones that a paralog was detected and therefore that locus shouldn't be on the schema.

**Comment by mickaelsilva** [comment]
NIPH could also mean that the isolate is contaminated. It's a flag for when 2 or more good hits are found for a single locus on the same isolate.

**Comment by jacarrico** [comment]
@moorembioinfo just tried myself with NC_009089.1 and found out the following: 

1) The alleles found that have different numbers are actually called by chewBBACA . They are not originally in the schema. They simply assume the smaller allele most probably

2) the LNF are indeed loci with less than 200bp. In chewBBACA we don't consider those loci. For example one of  the loci has only 73 bp (CD630_17671).

**Comment by moorembioinfo** [comment]
Hi @jacarrico that's correct it's the reference genome. With the LNF explained that's everything! 

The problem of alleles that are subsets of others will persist as long as the external scheme disagrees with prodigal then. I think for my purposes it will definitely be best to generate a new scheme for _C. difficile_!

Thanks so much both for your help! @jacarrico @mickaelsilva
