### ISSUE TITLE
chewBBACA as Galaxy Tools

### ISSUE THREAD

**Issue by ratzeni** [B-UMMI/chewBBACA#26]
Is it available as a Galaxy tool?

**Comment by mickaelsilva** [comment]
Not sure. @jacarrico

**Comment by jacarrico** [comment]
@ratzeni sorry for the delay in the reply but I was travelling. We don't have it per se but we know a group that has successfully implemented it as a galaxy module. If you send me your email I can put you in contact with them.
All the best

**Comment by ratzeni** [comment]
@jacarrico Thank you for your interest. Galaxy module is a good solution for my purposes. My email is ratzeni@crs4.it

**Comment by jacarrico** [comment]
@ratzeni Sorry for the delay in the reply but I can finally let you know that chewBBACA was added to the galaxy toolshed:
https://toolshed.g2.bx.psu.edu/repository?repository_id=88fd7663075eeae9&changeset_revision=093352878303

Credits for this work go to Arnold Knijn and Stefano Morabito from the EURL VTEC in Rome.

**Comment by ratzeni** [comment]
@jacarrico Thanks a lot! :)
