### ISSUE TITLE
Format change request for results_alleles.tsv

### ISSUE THREAD

**Issue by karinlag** [B-UMMI/chewBBACA#27]
We are working on clustering data from chewbbaca results, and we are using the results_alleles.tsv file. We here discovered that when a new allele is found, it is listed as INF-number. Then, the next time this one is seen, only the number is listed. Thus, inside this file the same allele is given effectively two different names. 

Our suggestion is that you instead give all instances of the new allele the INF-number name, which would make it easy to figure out for each isolate which ones are new and which ones are not new. In addition, it would mean that when using it for distance matrices, the fields would be regarded as "the same".

**Comment by jacarrico** [comment]
Hi Karin 
The raw output is not to be used for the calculation of the distance matrixes. For those you should use the ExtractCgMLST function of chewBBACA that will clean the output and will allow you to fine tune the schema.

**Comment by karinlag** [comment]
Just to follow up in that case:

We are using an enterobase cgMLST scheme. Would we just then do the extractcgmlst with -p at 0?

**Comment by mickaelsilva** [comment]
If you're ok with all missing data being replaced with 0 yes.

**Comment by karinlag** [comment]
I think that would ok. It would only be missing data that would be 0 yes, all others would be a number, yes?

**Comment by mickaelsilva** [comment]
That is correct.

**Comment by schorlton** [comment]
I suggest reopening this issue. This is not intuitive and I made the same error. I agree that if using the AlleleCall command, all new INF-* alleles should be converted to appear the same.

**Comment by ramirma** [comment]
As you may have seen above there is a way to get your expected behavior of making all alleles to be tagged the same way. Still, I will discuss this again with @pedrorvc and @rfm-targa.
