### ISSUE TITLE
pMLST schemes have 'no correct alleles' and are removed

### ISSUE THREAD

**Issue by JSHuisman** [B-UMMI/chewBBACA#30]
Dear chewBBACA developers,

Today I wanted to run PrepExternalSchema on a set of pMLST files downloaded from the pubMLSt database (https://pubmlst.org/bigsdb?db=pubmlst_plasmid_seqdef&page=downloadAlleles - renamed so that the files end on ".fasta"). I tried both IncI and IncF; but in both cases chewBBACA outputs:
"gene.fasta has no correct aleles, the file will be removed!!" for all genes in the scheme (and wipes all my files!).
I have previously used your software with a large cgMLST scheme downloaded from Enterobase and encountered no such problems.

(i) Do you know why these files are not being recognised properly by chewBBACA?
(ii) Why is the default behaviour to remove the content of all files without prior warning?

**Comment by mickaelsilva** [comment]
It's probably because chewbbaca uses CDS only sequences, hence we remove locus directly if they have no alleles that form a valid CDS

**Comment by JSHuisman** [comment]
To test this hypothesis I ran prodigal on 2 of the genes included in the pMLST scheme for IncI1, and both return CDS's for all alleles.
Without a training file the program complained because it needed at least 20000 characters; but when supplying the chewBBACA prodigal training file all ran fine.
Could it be that you're running prodigal without the training file?

**Comment by mickaelsilva** [comment]
Prodigal is not run on the locus files with chewbbaca, they should already be somehow curated previous to use in our opinion

I checked the the repA locus and the alleles are not even multiple of 3

**Comment by JSHuisman** [comment]
Isn't making the locus files compliant with the expected input of chewBBACA exactly what the "PrepExternalSchema" function does?

The pMLST schemes are curated carefully and widely used. As far as I know, they are subsequences of a set of known transfer and replication genes; as selected for a traditional primer-based MLST. Prodigal finds CDS within them (also in the repA of IncA/C) - as long as you supply a training file (because the locus files themselves are too short to train on). I thought this would be sufficient for chewBBACA to work, but clearly not.

What other requirements do you have for the locus files of an external scheme? And/or what format do you expect them to be in?

**Comment by jacarrico** [comment]
Dear @JSHuisman 
Yes "PrepExternalSchema" does exactly what you say. And to do that it has to validate if the locus are coding sequences that would be recognized as such by prodigal. Are the locus in the pMLST scheme , entire CDSs or are they fragments of each CDS similarly to traditional MLST schemas? 
It it is the latter , it won't work on chewBBACA. Furthermore if it is the first, it depends on how the authors defined the CDS. Several databases contain CDSs that have sequences that are not multiple of 3, which is a quick check to know if the coding sequencing is properly annotated.  
The "PrepExternalSchema" also creates the prototypes against those the BSR of each CDS identified by prodigal on the sequences that will be queried will be done. this is what will be added to the `/short` directory inside the schema directory. Other validations are similiar to what is described in the Allele Calling part of the wiki (https://github.com/B-UMMI/chewBBACA/wiki/2.-Allele-Calling)

**Comment by JSHuisman** [comment]
Dear @jacarrico ,
Thank you for your more detailed explanation. I believe they are fragments of each CDS, so that answers why it won't work with chewBBACA. Pity!
