### ISSUE TITLE
Unable to prepare schema from PubMLST schema profile of Helicobacter pylori

### ISSUE THREAD

**Issue by pixuenan** [B-UMMI/chewBBACA#33]
I tried the schema preparation from PubMLST schema profile of _Helicobacter pylori_ by using
`chewBBACA.py PrepExternalSchema -i hpylori_190410 -v`
, then I got error
`ATTENTION!!!111 
hpylori_190410/atpA.tfa.fasta has no correct aleles, the file will be removed!!`
Seems the problem is the locus in the schema are not intact CDS, such as the locus in the `atpa.tfa.fasta` file.

[atpA.tfa.fasta.zip](https://github.com/B-UMMI/chewBBACA/files/3101843/atpA.tfa.fasta.zip)

**Comment by jacarrico** [comment]
Greetings @pixuenan 
chewBBACA is not intended to be used in MLST schemas exactly by the reasons you pointed out. The used case for chewBBACA is cg/wgMLST schemas composed of loci  where alleles are "intact CDSs.
