### ISSUE TITLE
Allele id affects tree structure

### ISSUE THREAD

**Issue by pixuenan** [B-UMMI/chewBBACA#34]
Hi,

When I check the result profile from cgMLST, I found the assigned allele id for each strains does not actually reflect the sequence similarity but is the input order of the strain. So if the strain is the first input of the analysis, then all the allele id of each locus of this strain will have small number, e.g. 1, 2. If another strain which is the 1000th input, and all locus are different from the schema, then the allele id of each locus of this strain will have large number. If this is true, the sequence similarity between two allele with id 1 and 2 is actually the same as two allele with id 1 and 1000. I am worried that this will affect the reproducibility of the result, so with a cgMLST profile of 57 Yersinia strains, I random shuffle the allele id for each strain in each locus, and build RapidNJ Tree and Minimum Spanning Tree. I do found the tree structure changed, though not dramatically.

Am I get misunderstanding of the cgMLST?

**Comment by jacarrico** [comment]
In MLST / cgMLST/wgMLST/rMLST the allele Id is always a categorical numerical identifier. It does not reflect or was ever intended to reflect the similarity of the sequence based on the similarity of Ids. It would be impossible to  maintain such system as new sequences are always added to the schema. 
This being said any analysis based on allelic profiles can only be done based on hamming differences between profiles (i.e. number of different locus). If the tree structure changes that means that you are not using an hamming distance but probably an euclidian distance for the RapidNJ or Minimum Spanning Tree calculations.

**Comment by pixuenan** [comment]
Thanks for the clarification!
