### ISSUE TITLE
FileNotFound error --- Again

### ISSUE THREAD

**Issue by daniazi** [B-UMMI/chewBBACA#36]
Hi,

I am running chewBBACA version 2.0.17, and I am getting an error with AlleleCall. I trained C. jejuni genome using prodigal 2.6.0 (also tried latest v 2.6.3) by:

`prodigal -i Campylobacter_jejuni.fasta -c -m -p single -t C_jejuni.trn
`
> PRODIGAL v2.60 [October, 2011]         
> Univ of Tenn / Oak Ridge National Lab
> Doug Hyatt, Loren Hauser, et al.     
> Request:  Single Genome, Phase:  Training
> Reading in the sequence(s) to train...1641481 bp seq created, 30.55 pct GC
> Locating all potential starts and stops...46104 nodes
> Looking for GC bias in different frames...frame bias scores: 2.69 0.18 0.13
> Building initial set of genes to train from...done!
> Creating coding model and scoring nodes...done!
> Examining upstream regions and training starts...done!
> Writing data to training file C_jejuni.trn...done!

Followed by schema creation as follows which apparently worked well:
`chewBBACA.py CreateSchema -i ./Campy_jejuni_genomes/ -o C_jejuni_schema --ptf C_jejuni.trn --cpu 24`

> Total of 1704 loci that constitute the schema
> Starting Script at : 16:22:15-03/07/2019
> Finished Script at : 16:27:29-03/07/2019
> 

However when running the command:
`chewBBACA.py AlleleCall -i ./Campy_jejuni_genomes/ -g C_jejuni_schema/ -o results_ac --cpu 24 --ptf C_jejuni.trn`

I get the following error:

> Starting Allele Calling at : 16:31:30-03/07/2019
> Processing 6-R-protein2671.fasta. Start 16:31:43-03/07/2019 Locus 1703 of 1704. Done 99%.Finished Allele Calling at : 16:31:43-03/07/2019
> Wrapping up the results
> [Errno 2] No such file or directory: '/export/proj/camp_b_wgs/NOBACKUP/chewbbaca_analysis/C_jejuni_schema/temp/1-R-protein1053.fasta_result.txt'
> 

I get the same error while running tutorial data:

> Processing GCA-001683515-protein3881.fasta. Start 17:06:37-03/07/2019 Locus 3129 of 3130. Done 99%.Finished Allele Calling at : 17:06:38-03/07/2019
> Wrapping up the results
> [Errno 2] No such file or directory: '/export/proj/camp_b_wgs/NOBACKUP/chewBBACA_tutorial/schema_seed/temp/GCA-000007265-protein1.fasta_result.txt'
> 

The earlier post did not help in any way to resolve the problem. Any help will be much appreciated?

**Comment by mickaelsilva** [comment]
Did you try with the genome files from the tutorial or just the tutorial schema?

**Comment by daniazi** [comment]
I did try the tutorial data but got the same problem.

**Comment by mickaelsilva** [comment]
BLAST version?

**Comment by daniazi** [comment]
I do not know why but blast/2.9.0 solved the issue. Earlier I was running v2.6.0.
