### ISSUE TITLE
%i format: a number is required, not NoneType

### ISSUE THREAD

**Issue by eam12** [B-UMMI/chewBBACA#39]
I am trying to use the very large external scheme Enterobase Salmonella cgMLSTv2. After running `chewBBACA.py PrepExternalSchema`, I tried running `chewBBACA.py AlleleCall`, but I get the following errors. First, `'utf-8' codec can't decode byte` is repeated over and over again and then I get the following repeated over and over again:
```
some error occurred
%i format: a number is required, not NoneType
Error on line 466
```
I did get output files, but there are many `ERROR`s in the _results_alleles.tsv_ file. As far as I can tell, `PrepExternalSchema` ran correctly, minus the removal of two loci with no correct alleles (I'm assuming they're not complete CDS). If the input scheme is correct, do the errors I'm getting have to do with the contig FASTA files I'm using? Any help would be much appreciated. Thank you!

**Comment by rfm-targa** [comment]
Greetings,
Can you please check what's the Python version that is being called when running chewBBACA? It should be executed with Python>=3.4 just to be safe.

**Comment by eam12** [comment]
I double checked and I'm running chewBBACA with python 3.6.7 (as is the default in [bioconda](https://anaconda.org/bioconda/chewbbaca)).

**Comment by eam12** [comment]
Just an update, I realized there may have been an incompatibility issue between the version of python installed from bioconda (3.6.7) and the version I had running in the computer cluster I'm using (3.6.3). However, after uninstalling the cluster version of python I had running, but I am still getting the same error messages when I run `chewBBACA.py AlleleCall`:

> Checking all prodigal processes created the necessary files...
> All prodigal files necessary were created
> 
> Finishing Prodigal at : 11:20:02-29/07/2019
> Translating genomes
> Starting Genome Blast Db creation at : 11:21:21-29/07/2019
> Starting Allele Calling at : 11:21:40-29/07/2019
> Processing STM4351.fasta. Start 11:21:40-29/07/2019 Locus 13 of 3000. Done 0%.some error occurred
> %i format: a number is required, not NoneType
> Error on line 466
> some error occurred
> %i format: a number is required, not NoneType
> Error on line 466
> some error occurred
> %i format: a number is required, not NoneType

etc.

**Comment by rfm-targa** [comment]
Can you please confirm if you get the same errors with the tutorial? It is possible that something in the new schema is leading to that problem and running the tutorial would help us figure that out.

**Comment by eam12** [comment]
I can run `chewBBACA.py CreateSchema -i complete_genomes/ --cpu 6 -o schema_seed --ptf Streptococcus_agalactiae.trn` successfully, but when I run `chewBBACA.py AlleleCall -i complete_genomes/ -g schema_seed/ -o results_cg --cpu 6 --ptf Streptococcus_agalactiae.trn` I get the same errors as I get with my new schema:

> Finishing Prodigal at : 12:42:02-29/07/2019
> Translating genomes
> Starting Genome Blast Db creation at : 12:42:14-29/07/2019
> Starting Allele Calling at : 12:42:17-29/07/2019
> Processing GCA-000007265-protein51.fasta. Start 12:42:17-29/07/2019 Locus 5 of 3130. Done 0%.some error occurred
> %i format: a number is required, not NoneType
> Error on line 466
> some error occurred
> %i format: a number is required, not NoneType
> Error on line 466
> some error occurred
> %i format: a number is required, not NoneType
> Error on line 466
> some error occurred

etc.

**Comment by mickaelsilva** [comment]
prodigal version and chewbbaca version?

**Comment by eam12** [comment]
prodigal v.2.6.3
chewbbaca v.2.0.16

**Comment by rfm-targa** [comment]
We suggest that you install the latest version of chewBBACA and necessary dependencies. Use the version that is in this repository and not the version available in Conda. Retry the tutorial and please tell us if you still encounter the same problem. Not being able to successfully run the tutorial indicates that it might be a problem or conflict with software (and not because there is an issue with the data), so please update to the latest stable version.

**Comment by eam12** [comment]
I installed the latest version of chewBBACA (2.0.17) and its dependencies using `pip3 install chewbbaca --user`. Dependency versions:

- numpy 1.17.0
- scipy 1.3.0
- biopython 1.74
- plotly 4.0.0
- SPARQLWrapper 1.8.4
- pandas 0.25.0
- BLAST+ 2.8.1
- Prodigal 2.6.3

I am _still_ getting the same error messages when I run `chewBBACA.py AlleleCall -i complete_genomes/ -g schema_seed/ -o results_cg --cpu 6 --ptf Streptococcus_agalactiae.trn`.

**Comment by rfm-targa** [comment]
What is the system that you're using to run chewBBACA? If you haven't tried to run on a different system, please try to do so and let us know if you get the same error even after switching to another system. With all dependencies and the correct versions, the tutorial should complete successfully. Your problem might be related with the configuration of your current environment or other system-related issue.

**Comment by jeremiahyarmie** [comment]
Hi I'm just going to piggy back on this.

I posted in the thread on the tutorial repo about this same issue. I've updated all of my dependencies. Used the chewBBACA that is available on both conda and pip3, and have tried it on both my work UBUNTU station and my personal MacBook Air. They all come up with the same 466 error. But for some reason the first part of the tutorial also works entirely, i.e. I can produce the image from the first section of the tutorial--the one with the 95% plot.

I don't know what to do. Any further analyses I try to do won't work however :(

**Comment by mickaelsilva** [comment]
Can you zip the genes folder after the first allele call and send it to me  mickaelsilva (at) fm.ul.pt ?

**Comment by mickaelsilva** [comment]
@eam12 @jeremiahyarmie  the issue should be now fixes. Latest updates from biopython were giving error when trying to print(match) for some reason

should be working now on 2.0.17.2

let me know if it worked

**Comment by jeremiahyarmie** [comment]
it's working thank you!!!!! :')
