### ISSUE TITLE
chewbbaca report a new allele on a perfect match of an existing allele

### ISSUE THREAD

**Issue by adipi71** [B-UMMI/chewBBACA#42]
Dear support,

We are facing a very strange situation in using chewbbaca (we are using chewbbaca 2.0.13).
(files are in the zip archive here:[chewbbaca_issue.zip](https://github.com/B-UMMI/chewBBACA/files/3565961/chewbbaca_issue.zip))
 

We have a listeria sample (denovo file `denovo_spades_scaffolds.fasta`) where using the web app from Pasteur (https://bigsdb.pasteur.fr/cgi-bin/bigsdb/bigsdb.pl?db=pubmlst_listeria_seqdef&page=sequenceQuery), we get a perfect match (100%) with an allele (see `bigsdb_pasteur_res.csv`).

Using the same Pasteur schema with chewbbaca  we got a new allel. The Score of the new allele is higher of the allele with perfect match. Which is a bit counterintuitive.
(see `prodigal/denovo_spades_scaffolds.potential`, search with the start position "220843").

Additionally, searching with Blast produce the same result of Pasteur web app (see `blast` dir).

We experienced the same problem for several other alleles and samples. This leads to a lot of uncertainity. Samples that can be clearly related to an outbreak using Pasteur web app, are more distant in chewbbaca, thus leading to a not clear interpretation.

Do you have any hint for us?

Kind Regards,
Adriano Di Pasquale
Antonio Rinaldi

**Comment by cimendes** [comment]
Hello,

Could you please update to the latest Chewbbaca version (2.0.17.1) by cloning this repo and try again?

**Comment by mickaelsilva** [comment]
Hello, this issue has to do with how we detect the gene sequences on the genomes. If you compare the new allele found with the allele 22 you can see that  the new allele start on alternative start codon ATG instead of GTG used on pasteur allele.

It is something expected to happen

**Comment by adipi71** [comment]
Thank you both for the very rapid answers.
@mickaelsilva  : what you mention is exactly what happened, but the allele with GTG start codon is a perfect match of the pasteur allele. The question is why the choice is to create a new allele (to one with alternative start codon ATG). i.e., Why the perfect match pasteur allele has less score than the new one?

This  is just one of several other cases.

Can you justify the choice?

Is there some options to set chewbbaca to first choose existent (perfect match) alleles and then try to investigate for new ones?

**Comment by ramirma** [comment]
chewBBACA uses the open reading frames detected by Prodigal. This has the advantage that the allele call is consistent between calls and there is no propagation of any potential errors in the initial annotation. Moreover, chewBBACA was designed with the goal of identifying ORFs as alleles (you can read more on this in [chewBBACA's publication](https://www.ncbi.nlm.nih.gov/pubmed/29543149) whish is not a strictly "target" based schema as was the case of the 7-gene MLST schemas (in which the "targets" were defined by the primers used)

Of course prodigal may identify start sites that do not correspond to the start sites identified by experimental data. However, very few genes have actually been tested experimentally for the start of the translated protein and this information is not readily available, so we have opted for using the ORFs identified by Prodigal. Unfortunately when using a schema which was not originally created by  chewBBACA the situation you describe is frequent.

I hope this clarified your question.

**Comment by adipi71** [comment]
Thank you very much for your answers.

Let me continue with other questions. That is because we use chewBBACA for outbreak investigations for Italian National Reference Centre of Listeria monocytogenes and we wants to avoid any possible bad interpretation. In _Lm_ the schema Pasteur is more or less a standard de-facto. Have you ever launched "SchemaEvaluation" on that schema? (https://bigsdb.pasteur.fr/cgi-bin/bigsdb/bigsdb.pl?db=pubmlst_listeria_seqdef&page=downloadAlleles&scheme_id=3&render=1) or, concerning the sentence _"schema which was not originally created by chewBBACA the situation you describe is frequent"_,  how this can be done with this schema? 

Moreover, given a schema (that you trust), could be a suggestion to 
- first, find the **perfect matches alleles** from the schema (e.g., with BLASTN)
- launch chewBBACA
- give higher priority to the **perfect matches alleles** then to the chewBBACA ones?

What is your idea?

**Comment by rfm-targa** [comment]
Yes, we have used `SchemaEvaluator` to assess that schema from BIGSdb. We just need to search for the results and we'll tell you something (the schema evaluation results were good, as far as we recall).

Regarding the suggestions, we use Prodigal in the CreateSchema and AlleleCall processes to predict coding sequences and that allows us to achieve more consistent results than if we were using several methods to predict and decide which predictions are more correct. Adopting a different approach for external schemas would be difficult to implement and conciliate with the rest of the processes. The AlleleCall process starts by determining exact matches between alleles in the schema and coding sequences predicted by Prodigal. While it would be possible to start by searching the genomes/assemblies for exact matches in the external schema, followed by prediction with Prodigal, it would lead to inconsistent results and resolving conflicts between exact matches and Prodigal predictions would not be straightforward.
