### ISSUE TITLE
Prodigal training files to use - README instructions

### ISSUE THREAD

**Issue by cimendes** [B-UMMI/chewBBACA#47]
Hi,

In chewBBACA's README, in the IMPORTANT section, there's a warning that states that `As from 02/02/2018 prodigal training files to be used are now on a separate repository. You can find them at https://github.com/mickaelsilva/prodigal_training_files.` 

Currently, there are training files provided with chewbbaca's source code that aren't available at https://github.com/mickaelsilva/prodigal_training_files. I suggest either revise the README to state where this files can be found in the source code, or if the decision is to separate these from the source code, move them to a new repository inside the B-UMMI organization, and update the README accordingly. 

Best,

Inês

**Comment by pedrorvc** [comment]
Thank you for bringing that warning to our attention. 

The README.md has been updated accordingly.

**Comment by mdiricks** [comment]
Could you perhaps also give some more information in the readme files what the exact function is of the training files (at which step are they used), what they contain and what the implications are if you don´t use them?
