### ISSUE TITLE
[Errno 2] No such file or directory: ' '

### ISSUE THREAD

**Issue by JPegorino** [B-UMMI/chewBBACA#48]
I'm getting this error after 'checking gene files exist...' with chewBBACA 2.0.17.2 (anaconda) in a parallel interactive SGE HCC node (2 cores).

<img width="519" alt="ChewBBaca_issue" src="https://user-images.githubusercontent.com/54990643/68194531-19df4b00-ffad-11e9-9e3e-914814c4ca99.PNG">

chewbbaca_testrun_inlist.txt is a single-line list with the full path to a genome (contigs) and ./schema/ is a directory with only the multi-fasta files from here (https://www.cgmlst.org/ncs/schema/1025099/locus/). I haven't checked all 1521  files in ./shema/ manually but can't find anything unusual with quick grep commands. All paths exist and I'm running anaconda 5.3.1, Blast2.9.0+ and Prodigal 2.6.3. I'm not sure what 436 refers to.

I haven't used chewBBACA or done cgMLST calling before, so I apologise if it's just me doing something really daft but can't seem to troubleshoot this one.

**Comment by rfm-targa** [comment]
Hello!

The AlleleCall process should be executed with schemas that were created with the CreateSchema process. I'm not sure if that is the problem, but you're using an external schema that was not created with the CreateSchema process from chewBBACA, right?

**Comment by JPegorino** [comment]
That's correct - I'm trying to use an existing cgMLST schema for L.pneumophila (1025099 - see above link)

**Comment by cimendes** [comment]
Hello! You'll need to use chewBBACA's `PrepExternalSchema` prior to the `AlleleCall` when using a schema that was not built with this tool. Please not that the latest version of chewbbaca (v 2.1.0) added a major over improvement on this function. I would strongly advise you to update chewBBACA beforehand (it's available on pip and conda).

**Comment by JPegorino** [comment]
Yes, running PrepExternalSchema prior to AlleleCall prevents this error. 
Thank you both for the rapid responses!
