### ISSUE TITLE
pip3 install doesn't work - could not find version

### ISSUE THREAD

**Issue by tseemann** [B-UMMI/chewBBACA#5]
```
% pip3 install chewBBACA
Collecting chewBBACA
  Could not find a version that satisfies the requirement chewBBACA (from versions: )
No matching distribution found for chewBBACA

% pip3 search chewBBACA
chewBBACA (2.0.5)  - A complete suite for gene-by-gene schema creation and strain identification

```

Any ideas?

I notice the instructions say` chewbbaca`, the repo is `chewBBACA` and the module is `CHEWBBACA` - could that be it?

**Comment by andersgs** [comment]
We figured out that this was an issue with how our `pip` was configured (`no-binary = :all:`) in order to play nicely with `brew` python. But, `chewBBACA` is only shared as a wheel on `pypi`. By explicitly saying `no-binary = :none:` it installed... Now, hopefully, we can see it do its magic!!! :)

**Comment by mickaelsilva** [comment]
Thanks for trying chewBBACA and for the feedback. I see you already managed to solve your own issue and I'm sure it will be helpful to someone else too.

Regarding the uppercase on the name, pip is case insensitive :)

**Comment by tseemann** [comment]
@andersgs  said: "But, chewBBACA is only shared as a wheel on pypi"

Is there something @mickaelsilva can do that helps here?
Or is all out fault only?

**Comment by andersgs** [comment]
When creating the files for distribution, it is customary to also run `python setup sdist`, which creates the source distribution. I suspect only `python setup bdist_wheel` was run.

**Comment by andersgs** [comment]
`pip` is only case-insensitive from version ≥6 (I believe). If you have this problem, make sure to run `pip install -U pip` to get the very latest version.

**Comment by mickaelsilva** [comment]
I guess I had missed that `python setup sdist` step. I'll make sure to do it next time. Thanks for the suggestion.

**Comment by mickaelsilva** [comment]
version 2.0.6 now as also the source distribution
