### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by andersgs** [B-UMMI/chewBBACA#51]
Hi @mickaelsilva. 

Love chewBBACA. I see there have been a number of commits since the last release on PyPI. When are you planning a new release?

Thank you.

Anders.

**Comment by ramirma** [comment]
Hi @andersgs,

@mickaelsilva has left the lab and, although he is graciously still answering support questions and helping us with some aspects of chewBBACA's development, he is no longer the main developer. @rfm-targa and @pedrorvc are now actively working on several improvements of chewBBACA, which we hope will translate into a major new release in the first quarter of 2020.  In the meantime, we will certainly consider intermediate releases in PyPI. Thanks for the heads up!

Mario

**Comment by rfm-targa** [comment]
Hello @andersgs ,

The latest version of chewBBACA, 2.1.0, has been added to PyPI.
Thank you for mentioning this subject.

**Comment by andersgs** [comment]
Awesome. Thank you!!! Feliz final de ano.
