### ISSUE TITLE
How to retrieve original prodigal gene sequence?

### ISSUE THREAD

**Issue by FilipeMatteoli** [B-UMMI/chewBBACA#60]
Hello friends, I have successfully created a cgMLST schema that has 2896 alleles out of 600 genomes, using 99% cutoff. I would like to fetch the original sequences predicted by prodigal for each genome so I could identify recombination sites on cgMLST alleles.

I started using the allele ID output in cgMLSTschema.txt, this has exactly 2896 lines. When I inspected these files, they do not have 600 sequences within but harbor a variable number of sequences according to the number of alleles.

Well after digging I noticed that I just need a script to search allele matrix file and fetch the sequence upon allele number. 

Best,

**Comment by rfm-targa** [comment]
Hello @FilipeMatteoli ,

The folder with the schema has 1 Fasta file per gene and a sub-directory named 'short'. Each Fasta file has all the alleles that were identified for a gene and each allele ends with an integer identifier. The matrix with the allele calling results has the identifiers of the alleles found for each genome (rows are genomes, columns are schema genes). Just as you determined, you can use the identifiers in the matrix to get the allele sequences if you extract the allele with the same identifier from the gene's Fasta file. chewBBACA's current version does not include a script/module to help with this type of operations.
The 'short' directory has Fasta files that contain only the representative sequences for each gene. The representative sequences are used to search for new alleles during the allele calling process.

If you need any information or assistance to work with the results and get what you want, please let us know. We'll gladly assist.
