### ISSUE TITLE
chewBBCA v2.1.0 Errno21 error on input directory

### ISSUE THREAD

**Issue by HanneloreH** [B-UMMI/chewBBACA#62]
Hello,

I have chewBBACA version 2.1.0, I used it just fine for several months until yesterday when suddenly started having this "Errno21: Is a directory:..." error. I noticed this error has been discussed here before concerning the short folder in the scheme directory but this was already solved in my version of chewBBACA and my problem concerns the input directory. I tried uninstalling/reinstalling the package but this did not solve the problem.

May it have been related with some installations and updates I did of other software perhaps(?)

Example code:

$ chewBBACA.py AlleleCall -i assembly/ -g ~/Data/cgMLSTschemes/MLST-573/cgMLST/scheme-573/ -o TEST --cpu 2

chewBBACA version 2.1.0 by Mickael Silva at https://github.com/B-UMMI/chewBBACA
email contact: mickaelsilva@medicina.ulisboa.pt
**[Errno 21] Is a directory: 'assembly/'**
	USAGE : chewBBACA.py [module] -h 

Thank you in advance

**Comment by rfm-targa** [comment]
Hello @HanneloreH 

We've identified the problem you described. It happens in version 2.1.0 and is related with a line of code where we use a BioPython function. As you said, it was not happening before and should be related with changes made to the BioPython package.

We advise you to clone the master branch and install chewBBACA in a new environment. You can then retry AlleleCall and you should not get that error. 
The latest version has some changes and the AlleleCall process will detect that your schema is from an older version. It will ask you if you want to proceed. If you accept, it will add a configuration file to your schema and store the parameters you're using in that file. It will not change the structure of your schema or remove/add/alter any sequence. If you use the default argument levels, just accept and it will continue as normal. The Prodigal training file that you include in the command will be copied to the schema directory and the AlleleCall process will expect you to use the same training file in subsequent runs. If you don't want to be bothered and prefer for it to add your configurations and continue automatically, you may use the `--fc` argument.

We also have a new release that you should be able to install via pip. That version should work well for your case, but we've identified a bug related with one of the new processes that we've implemented. We've already pushed a bugfix to the master branch and we'll create a new release (v2.5.1) soon.

Let us know if updating to the latest version solves this issue.

**Comment by HanneloreH** [comment]
Hello @rfm-targa,

This worked, thank you!

Only difference is that my assemblies used to be in ".fa" format and now it only seems to accept ".fasta". Not a big problem, but I wondered whether this was adjustable?
`
"Exception: There were no FASTA files in the given directory. Please provide a directorywith FASTA files or a file with the list of full paths to the FASTA files."
`

Kind regards,
Hannelore

**Comment by rfm-targa** [comment]
Hello @HanneloreH,

Glad it worked. Yes, we can adjust that. It accepts files with ".fasta", "'.fna" and ".ffn" suffixes. We'll add the ".fa" suffix in the next push. We'll update the message and exit cleanly, without traceback.

**Comment by rfm-targa** [comment]
Hello @HanneloreH,

We've added the ".fa" suffix and changes the exit message (e39b99067d4c8fa2ea633fb669a22a85bb946510).
We consider that this issue has been solved and we'll close it. Please reopen the issue if there's something else.

Best regards,
rfm
