### ISSUE TITLE
Cant find my files

### ISSUE THREAD

**Issue by Akllarena** [B-UMMI/chewBBACA#64]
Hi!

Stupid question, but I've been running chewbbaca (v2.0.17) for some time, and ive never had this issue before.

I have tried several things, including copying commands I have used successfully in the past, but I get the same error:
Starting Script at : 12:20:21-19/08/2020
checking if genome files exist..
checking if gene files exist..
436
[Errno 2] No such file or directory: ''
[Errno 2] No such file or directory: ''

        USAGE : chewBBACA.py [module] -h

My command is: 
chewBBACA.py AlleleCall -i genomes_shovill_all/ -g ~/chewbacca_wrkdir/schema/Campylobacter_jejuni/Schema/schema_seed_campy_roary_V5/ -o test_shovill --cpu 3 --ptf ~/chewbacca_wrkdir/prodigal_training_files/Campylobacter_jejuni.trn

My system is:
CentOS Linux release 7.8.2003 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"CentOS Linux release 7.8.2003 (Core)
CentOS Linux release 7.8.2003 (Core)

Thanks ! :)

**Comment by rfm-targa** [comment]
Hello @Akllarena,

Have you used the same schema in previous analyses without issues? Please verify that the schema's directory does not contain any invalid files with invalid data. Also, draft assemblies of poor quality might lead to empty results and problems with file reading and writing, so please verify the quality of the assemblies. If directory and file structure look ok, please run the same command but provide full paths to all arguments to rule out possible issues with directory/file path processing.
You may also try to install the latest version, v2.5.4, and run the AlleleCall process to check if it solves your issue and let us know if it is version specific.

To help us identify the problem can you post a comment with the full text outputted to the standard output by chewBBACA?

**Comment by Akllarena** [comment]
Hei, thanks for helping!
I have used the same schema before, without problems. Latest on monday, then it worked. Its the INNUENDO C. jejuni schema. 
I have some shitty assemblies, but I also tested w high quality assemblies and got the same error.
I have also done full paths to all arguments, no difference there. 
Ive also tried to install the latest version, but ran into issues both with pip and conda installation, I think I need to chat to my cluster boss about figuring that one out.

Here is what chewbbaca throws back at me. What I could do is to download the schema again. Might maybe help, maybe i did something to it??
(ChewBBACA) [annll@login-0 Campylobacter_jejuni]$ chewBBACA.py AlleleCall -i Genomes/chicken_human2014/ -g cgMLST678_w_path.txt -o test --cpu 4 --ptf ../../prodigal_training_files/Campylobacter_jejuni.trn
chewBBACA version 2.0.17.1 by Mickael Silva at https://github.com/B-UMMI/chewBBACA
email contact: mickaelsilva@medicina.ulisboa.pt


Warning, you are close to use all your cpus, if you are using a laptop you may be uncapable to perform any action
will use this training file : /net/fs-1/home01/annll/chewbacca_wrkdir/prodigal_training_files/Campylobacter_jejuni.trn
blastp
Will use this number of cpus: 4
Checking all programs are installed
Checking Blast installed... True
Checking Prodigal installed... True
blast version is up to date, the program will continue

Starting Script at : 21:40:54-19/08/2020
checking if genome files exist..
checking if gene files exist..
436
[Errno 2] No such file or directory: ''
[Errno 2] No such file or directory: ''

        USAGE : chewBBACA.py [module] -h

Select one of the following functions :

CreateSchema : Create a gene by gene schema based on genomes
AlleleCall : Perform allele call for target genomes
SchemaEvaluator : Tool that builds an html output to better navigate/visualize your schema
TestGenomeQuality : Analyze your allele call output to refine schemas
ExtractCgMLST : Select a subset of loci without missing data (to be used as PHYLOViZ input)
RemoveGenes : Remove a provided list of loci from your allele call output
PrepExternalSchema : prepare an external schema to be used by chewBBACA
JoinProfiles : join two profiles in a single profile file
UniprotFinder : get info about a schema created with chewBBACA

**Comment by Akllarena** [comment]
Never mind, and sorry! I think I must have corrupted my schema somehow; i renewed it and now it works like a charm. Have a nice.

**Comment by rfm-targa** [comment]
Good to know that you found the problem. Let us know if you run into any other issue.

**Comment by rfm-targa** [comment]
Closing issue. Feel free to reopen if the issue resurfaces and seems to be related with how chewBBACA works.
