### ISSUE TITLE
Clustalw2 Check failed

### ISSUE THREAD

**Issue by ISskandaR** [B-UMMI/chewBBACA#66]
Hi dears,
above all I wanna thanks you for your work; it's been extremely precious in my STRAIN profiling task.
I wanna just advise you that in SchemaEvaluator it look for a clustalw2 that actually dosn't exist because 
any of the installation produce a lin "clustalw".
I solved that by correcting its name  in the relative  script holded in 
 ~/anaconda3/lib/python3.8/site-packages/CHEWBBACA/SchemaEvaluator
I hope that help

Best regards
Valentino Costabile
Bioinformaticians

**Comment by rfm-targa** [comment]
Hello @ISskandaR,

The SchemaEvaluator module has some dependencies that are no longer maintained and it may give incomplete results depending on the state of the installed dependencies. We will try to fix these issues in a future release. For now, the SchemaEvaluator module can still be used, albeit with some issues.
If you install chewBBACA through conda, clustalw2 should be installed and the SchemaEvaluator module should output the following text to the stdout:

```
...
Starting Script at : 16:16:00-16/10/2020
Checking all programs are installed
Checking mafft installed... True
Checking clustalw2 installed... True
...
```

If you install through Pip or from source, you will need to install clustalw2 and mafft and add them to PATH.

**Comment by ISskandaR** [comment]
Hi dears,
Actually I've installed chewBBACA with Conda  and it works fine for
everything; the issue I was reporting regards the alias used for clustalw
since any of the distributed package provide
the command clustalw2  but just clustalw independently from the version
used, as I corrected its name in the pyscript I solved the initial error
complaining about the absence of clustalw2
(even if I already had clustalw 2.1 in my variable path).
I hope this help
Best regards

Valentino



Il giorno ven 16 ott 2020 alle ore 17:26 Rafael Mamede <
notifications@github.com> ha scritto:

**Comment by rfm-targa** [comment]
Hello @ISskandaR,

Can you provide more information about the error/behaviour you got when you noticed that issue? If it is not much to ask, can you tell us the file and lines that you have altered? We want to make sure that clustalw is always called as expected.
Thank you a lot.

Best regards,

rfm

**Comment by ISskandaR** [comment]
Hi Rafael,
The error was returned during schemaEvaluation step , in particular during
the installation path check for mafft and clustalw:

...
Starting Script at : 16:16:00-16/10/2020
Checking all programs are installed
Checking mafft installed... True
Checking clustalw2 installed... False

So i accessed to script ValidateSchema.py located in:
~/anaconda3/pkgs/chewbbaca-2.5.5-py_0/site-packages/CHEWBBACA/SchemaEvaluator/ValidateSchema.py
(since I have conda installation)
And i simply changed the line 45 :
    print ("Checking clustalw2 installed... " + str(which('clustalw2')))
in
    print ("Checking clustalw installed... " + str(which('clustalw')))
And everything worked fine.
If you need more info just text me.
Still thanks for your great job

Valentino


Il giorno mer 21 ott 2020 alle ore 20:15 Rafael Mamede <
notifications@github.com> ha scritto:

**Comment by rfm-targa** [comment]
Hello @ISskandaR.

Thank you for all your feedback. We are working on a new version of `SchemaEvaluator` that fixes several issues with that process. The updated code will perform installation and version checks in a different way and the issue you have reported will be solved.

I will close this issue, but feel free to reopen if you want to report additional info about this or related issues.

Best regards,

rfm

**Comment by ISskandaR** [comment]
I've been glad to help you;
I'll look forward for your next release
Best Regards

Valentino

Il giorno gio 5 nov 2020 alle ore 20:09 Rafael Mamede <
notifications@github.com> ha scritto:
