### ISSUE TITLE
Version bugfix

### ISSUE THREAD

**Issue by pedrorvc** [B-UMMI/chewBBACA#70]
https://github.com/B-UMMI/chewBBACA/blob/0b81f4f3b501f7ac49a404eb93c0ad2205ac7122/CHEWBBACA/chewBBACA.py#L1543

Running `chewBBACA.py -v` does not print the version. Instead, the help message is printed.

**Comment by pedrorvc** [comment]
Waiting for testing before making the PR.

**Comment by rfm-targa** [comment]
This issue has been fixed. Closing issue.
