### ISSUE TITLE
newly inferred alleles issue in ExtractCgMLST output

### ISSUE THREAD

**Issue by eam12** [B-UMMI/chewBBACA#81]
I am looking to create a minimum spanning tree from my chewBBACA (version 2.5.6) results using the software [GrapeTree](https://enterobase.readthedocs.io/en/latest/grapetree/grapetree-about.html). This requires a formatted text file where 

> [t]he first row contains the headers for each column “Name”, “ST” (Sequence Type), and each subsequent column are the names of locus within the cgMLST scheme.

However, chewBBACA's `cgMLST.tsv` output file from the `ExtractCgMLST` function is not adaptable to GrapeTree because there is inconsistent naming of newly inferred alleles. Specifically, as was brought up in issue #27, for the `results_alleles.tsv` file, 

> when a new allele is found, it is listed as INF-number. Then, the next time this one is seen, only the number is listed. Thus, inside this file the same allele is given effectively two different names.

It was suggested to

> use the `ExtractCgMLST` function of chewBBACA that will clean the output and will allow you to fine tune the schema

However, I am still getting the same issue in the `cgMLST.tsv` file of `ExtractCgMLST`. For example:

FILE | STM0942.fasta | STM1940.fasta | STM3624.fasta
-- | -- | -- | --
sample1 | 10 | INF-3215 | 10
sample2 | 10 | 3215 | 10
sample3 | 10 | 3215 | 10

Additionally, I am getting non-numeric allele classifications such as `NIPH `, `LNF`, and `PLOT5` in the `cgMLST.tsv` file of `ExtractCgMLST`. For example:

FILE | STMMW_00121.fasta | STMMW_00131.fasta | STMMW_00141.fasta
-- | -- | -- | --
sample1 | 10 | 10 | 1
sample2 | 10 | 10 | LNF
sample3 | 10 | PLOT5 | LNF

Is there another "clean" output file somewhere that I am missing, or do I need to work off of `cgMLST.tsv` and just modify things manually?

Thank you!

**Comment by rfm-targa** [comment]
Hello @eam12,

Thank you for using chewBBACA and for reporting this issue.
The `ExtractCgMLST` process should remove `INF-` and `*` from profiles and convert remaining non-numerical data to `0` (this includes LNF, PLOT3, PLOT5, ASM, ALM, etc).
We added some changes to the main branch that fix this issue. We will create a new release in PyPI and Conda that will include these changes. In the meantime, you can clone the main branch and run the `ExtractCgMLST` process to 'clean' the matrix created by `AlleleCall` (the releases in PyPI will be available soon, the release in Conda can take a little longer to be accepted).
Please let us know if the latest changes fixed the issue or if you need anything else.

rfm

**Comment by eam12** [comment]
Looks like the changes have fixed the issue. Thank you so much!

**Comment by rfm-targa** [comment]
@eam12, chewBBACA's latest version ([2.6.0](https://github.com/B-UMMI/chewBBACA#260)) can be installed through pip and conda. It includes the fix for the [ExtractCgMLST](https://github.com/B-UMMI/chewBBACA/wiki/3.-cgMLST-definition#33-creating-the-cgmlst-schema) process and the new implementation of the [SchemaEvaluator](https://github.com/B-UMMI/chewBBACA/wiki/4.-Schema-Evaluation#evaluate-schema) process. If possible, give it a try and let us know about any issues.
