### ISSUE TITLE
Include a useful symlink

### ISSUE THREAD

**Issue by tseemann** [B-UMMI/chewBBACA#9]
`chewBBACA.py` is difficult to remember and type.

Can you addirtionally include a symlink eg. `chewie` for the rest of us?

**Comment by mickaelsilva** [comment]
Package updated. `chewie` should now be usable the same way as  `chewBBACA.py`.

**Comment by tseemann** [comment]
Thank you, it works, but if you give no parameters to `chewie` it fails:

```
chewie
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/chewie", line 11, in <module>
    load_entry_point('chewBBACA==2.0.7', 'console_scripts', 'chewie')()
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.6/site-packages/CHEWBBACA/chewBBACA.py", line 373, in main
    if "version" in sys.argv[1]:
IndexError: list index out of range
```

**Comment by mickaelsilva** [comment]
Thanks, should be corrected now.

**Comment by mickaelsilva** [comment]
Thanks for the suggestion, I'm also using chewie now :)
