### ISSUE TITLE
How to convert results alleles to make a tree?

### ISSUE THREAD

**Issue by galstriker** [B-UMMI/chewBBACA#90]
Hi , I ran a cgMLST on existing schema using chewBBACA. The output "results_alleles.tsv" contain many alleles like "LNF". How can I use this file to make a MST？I read the tutorial there was a way to convert this file (cgmlst-dist ?). Or may I just put it into phyloviz without any other change? Thanks.

**Comment by rfm-targa** [comment]
Hello @galstriker,

The `ExtractCgMLST` process can be used to convert the `NIPH`, `NIPHEM`, `ASM`, `ALM`, `PLOT` and `LNF` classifications into 0 and remove the `INF-` prefix from newly inferred alleles. Simply pass the `results_alleles.tsv` file to the `ExtractCgMLST` process to determine the cgMLST with a threshold value of `0`. A sample command would be the following:

```
chewBBACA.py ExtractCgMLST -i results_alleles.tsv -o cgMLST --t 0
```

This will create a directory named `cgMLST` that contains several files, including the `cgMLST.tsv` file that contains the converted allelic profiles that can be imported into PHYLOViZ.

Let us know if this solves the issue.

**Comment by galstriker** [comment]
> Hello @galstriker,
> 
> The `ExtractCgMLST` process can be used to convert the `NIPH`, `NIPHEM`, `ASM`, `ALM`, `PLOT` and `LNF` classifications into 0 and remove the `INF-` prefix from newly inferred alleles. Simply pass the `results_alleles.tsv` file to the `ExtractCgMLST` process to determine the cgMLST with a threshold value of `0`. A sample command would be the following:
> 
> ```
> chewBBACA.py ExtractCgMLST -i results_alleles.tsv -o cgMLST --t 0
> ```
> 
> This will create a directory named `cgMLST` that contains several files, including the `cgMLST.tsv` file that contains the converted allelic profiles that can be imported into PHYLOViZ.
> 
> Let us know if this solves the issue.

Hi @rfm-targa , thanks for answering my question. I followed your command above but did not found the "--t" but I found the "--p" . When I set "--p" to "0", the file cgMLST.tsv still had the "LNF" in it. The chewBBACA version I used was 2.5.6. Command:
``
chewBBACA.py ExtractCgMLST -i results_alleles.tsv -o cgmlstclean/ --p 0
``
Thanks.

**Comment by rfm-targa** [comment]
Hello @galstriker,

The `ExtractCgMLST` process was updated in version 2.7.0 to correct a bug related with the conversion of values in the allelic profiles. Please update to chewBBACA v2.7.0 to get the latest release that includes the bugfix. You can update with the following command if you are working on a conda environment:

```
conda update chewbbaca
```

or

```
pip install chewbbaca --upgrade
```

if you are using pip.
We also recommend that you use BLAST v2.9.0.
Let us know if this solves your issue.

**Comment by galstriker** [comment]
Hello @rfm-targa , after I updated the chewBBACA to 2.7.0, when I AlleleCall with the schema created by chewBBACA 2.7.0, it reported like this:
```
chewBBACA version: 2.7.0
Authors: Mickael Silva, Pedro Cerqueira, Rafael Mamede
Github: https://github.com/B-UMMI/chewBBACA
Wiki: https://github.com/B-UMMI/chewBBACA/wiki
Tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
Contacts: imm-bioinfo@medicina.ulisboa.pt

==========================
  chewBBACA - AlleleCall
==========================
Started at: 2021-04-13T12:43:40

It seems that your schema was created with chewBBACA 2.1.0 or lower.
It is highly recommended that you run the PrepExternalSchema process to guarantee full compatibility with the new chewBBACA version.
If you wish to continue, the AlleleCall process will convert the schema to v2.7.0, but will not determine if schema structure respects configuration values.
Do you wish to proceed?
Traceback (most recent call last):
```
However, the schema I used was created by 2.7.0. What should I do ? I didn't encountered this wrong when I used chewBBACA 2.5.6. 
Thanks.

**Comment by rfm-targa** [comment]
Hello @galstriker,

chewBBACA v2.7.0 creates a folder with the schema inside the directory that you pass to the `-o` parameter in the `CreateSchema` process. Please verify the command you have used to perform allele calling and make sure that the `-g` parameter that you pass to the `AlleleCall` process matches the schema's directory (e.g.: if you passed `/home/user/my_schema` to the `-o` parameter in the `CreateSchema` process, the schema will be in `/home/user/my_schema/schema_seed`. The schema's default name is `schema_seed`, but that name can be changed through the `--n` parameter in the `CreateSchema` process). Let us know if this solves the issue.

**Comment by galstriker** [comment]
Hello @rfm-targa,
I followed the "chewBBACA_tutorial" to create the schema, when I prerared to AlleleCall after "Paralog detection", I met the error above. My command like this:
```
chewBBACA.py AlleleCall -i fna/ -g cgmlst/step2/result_cg/results_20210412T213246/testquality_step4/Gene_95%_115_addpath.txt -o result_step5 --cpu 80 --ptf Escherichia_coli.trn
```
The gene list file I had added the full path in the schema to each locus, but I still could not run the command. 
Thanks.

**Comment by rfm-targa** [comment]
Hello @galstriker,

We tested the `AlleleCall` process with a list of genes as input and it is not working properly. We are working on a fix for this issue and will let you know when there is a new release. This is a simple issue and we expect to be able to create the new release tomorrow.
Thank you for reporting this issue.

**Comment by rfm-targa** [comment]
Hello @galstriker,

Sorry for the delayed response. We have updated chewBBACA to v2.8.4. You can install it with [pip](https://pypi.org/project/chewBBACA/) or [conda](https://anaconda.org/bioconda/chewbbaca). We have added a new parameter to the `AlleleCall` process, `--gl`, `--genes-list`, that can be used to pass the list of genes (with or without the full path). A sample command would be the following:

`chewBBACA.py -i /path/to/InputAssemblies -g /path/to/SchemaName --gl /path/to/GenesList.txt -o /path/to/OutputFolderName`

It will perform allele calling for all genes in the schema if you do not provide the `--gl` parameter. It is not necessary to provide the full path to each gene file. The `GenesList.txt` should have the following structure:

```
gene1_id.fasta
gene2_id.fasta
gene3_id.fasta
...
```

Please let us know if the latest version solves this issue.
