### ISSUE TITLE
blast: Error in command-line arguments.

### ISSUE THREAD

**Issue by valeriaR89** [B-UMMI/chewBBACA#94]
Dear developers,
I had this error message and I don't understand what is the problem:

______________
chewBBACA.py AlleleCall -i /storage/assembly/ -g chewbacca_wrkDIR/Listeria/ -o /storage/assembly/results --ptf chewbacca_wrkDIR/prodigal_training_files/Listeria_monocytogenes.trn --cpu 10

chewBBACA version: 2.7.0
Authors: Mickael Silva, Pedro Cerqueira, Rafael Mamede
Github: https://github.com/B-UMMI/chewBBACA
Wiki: https://github.com/B-UMMI/chewBBACA/wiki
Tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
Contacts: imm-bioinfo@medicina.ulisboa.pt

==========================
  chewBBACA - AlleleCall
==========================
Started at: 2021-04-19T11:45:08

Checking if genome files exist...
Checking if gene files exist...

Starting Prodigal at: 11:45:09-19/04/2021
Training file: chewbacca_wrkDIR/prodigal_training_files/Listeria_monocytogenes.trn
 [====================] 100%
Finishing Prodigal at: 11:45:45-19/04/2021

Checking if Prodigal created all the necessary files...
All files were created.

Translating genomes...
Creating Blast databases for all genomes...

USAGE
  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
    -dbtype molecule_type [-title database_title] [-parse_seqids]
    [-hash_index] [-mask_data mask_data_files] [-mask_id mask_algo_ids]
    [-mask_desc mask_algo_descriptions] [-gi_mask]
    [-gi_mask_name gi_based_mask_names] [-out database_name]
    [-blastdb_version version] [-max_file_sz number_of_bytes]
    [-logfile File_Name] [-taxid TaxID] [-taxid_map TaxIDMapFile] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.10.1+

Use '-help' to print detailed descriptions of command line arguments
Error in command-line arguments. See error logs for more details.
========================================================================

USAGE
  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
    -dbtype molecule_type [-title database_title] [-parse_seqids]
    [-hash_index] [-mask_data mask_data_files] [-mask_id mask_algo_ids]
    [-mask_desc mask_algo_descriptions] [-gi_mask]
    [-gi_mask_name gi_based_mask_names] [-out database_name]
    [-blastdb_version version] [-max_file_sz number_of_bytes]
    [-logfile File_Name] [-taxid TaxID] [-taxid_map TaxIDMapFile] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.10.1+

Use '-help' to print detailed descriptions of command line arguments
Error in command-line arguments. See error logs for more details.
========================================================================

USAGE
  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
    -dbtype molecule_type [-title database_title] [-parse_seqids]
    [-hash_index] [-mask_data mask_data_files] [-mask_id mask_algo_ids]
    [-mask_desc mask_algo_descriptions] [-gi_mask]
    [-gi_mask_name gi_based_mask_names] [-out database_name]
    [-blastdb_version version] [-max_file_sz number_of_bytes]
    [-logfile File_Name] [-taxid TaxID] [-taxid_map TaxIDMapFile] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.10.1+

Use '-help' to print detailed descriptions of command line arguments
Error in command-line arguments. See error logs for more details.
========================================================================

Starting Allele Calling at: 11:45:49-19/04/2021
Processing lmo0272.fasta. Start 11:46:38-19/04/2021 Locus 1747 of 1748. Done 99%.
Finished Allele Calling at: 11:46:40-19/04/2021

Wrapping up the results...
Traceback (most recent call last):
  File "/home/.local/bin/chewBBACA.py", line 8, in <module>
    sys.exit(main())
  File "/home/.local/lib/python3.8/site-packages/CHEWBBACA/chewBBACA.py", line 1414, in main
    functions_info[process][1]()
  File "/home/.local/lib/python3.8/site-packages/CHEWBBACA/utils/process_datetime.py", line 149, in wrapper
    func(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/CHEWBBACA/chewBBACA.py", line 402, in allele_call
    BBACA.main(genomes_files, schema_genes, args.cpu_cores,
  File "/home/.local/lib/python3.8/site-packages/CHEWBBACA/allelecall/BBACA.py", line 446, in main
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'chewbacca_wrkDIR/Listeria/temp/lmo0055.fasta_result.txt'

___________

No results were produced. I thought the problem might be BLAST but I don't understand what is the problem.

Thank you for your kind help

Valeria

**Comment by valeriaR89** [comment]
The error was a blank space in the name of one assembly. Thank you

**Comment by rfm-targa** [comment]
Hello @valeriaR89,

Thank you for reporting this. Could you please share the name of the assembly that led to the error? It might help us to improve the code to deal with similar cases. Thank you.

rfm
