### ISSUE TITLE
UnboundLocalError: local variable 'list_files' referenced before assignment

### ISSUE THREAD

**Issue by zx26867** [B-UMMI/chewBBACA#95]
bug found when running allelic call

![Screen Shot 2021-04-20 at 6 54 37 PM](https://user-images.githubusercontent.com/60988182/115473622-07d98280-a20a-11eb-810b-26c974e42c99.png)

**Comment by rfm-targa** [comment]
Hello @zx26867,

We have updated chewBBACA to v2.8.4. You can install it through [pip](https://pypi.org/project/chewBBACA/) or [conda](https://anaconda.org/bioconda/chewbbaca). The latest version should work properly when a text file with full paths to input genome assemblies is passed to the `-i` parameter. The file with the list of input assemblies should have the following structure:

```
/path/to/input1.fasta
/path/to/input2.fasta
/path/to/input3.fasta
...
```

We have also added a new parameter to the `AlleleCall` process, `--gl`, `--genes-list`, that can be used to pass the list of genes (with or without the full path). A sample command would be the following:

`chewBBACA.py -i /path/to/InputAssemblies -g /path/to/SchemaName --gl /path/to/GenesList.txt -o /path/to/OutputFolderName`

It will perform allele calling for all genes in the schema if you do not provide the `--gl` parameter. It is not necessary to provide the full path to each gene file. The `GenesList.txt` should have the following structure:

```
gene1_id.fasta
gene2_id.fasta
gene3_id.fasta
...
```

**Comment by zx26867** [comment]
Thank you! I will try it next time.
